### ISSUE TITLE
Object for inner schema not generated

### ISSUE THREAD

**Issue by emsa23** [go-swagger/go-swagger#827] opened 2016-12-29 17:40 UTC
## Problem statement

I have a valid definition that generates but it seems like the inner schema object is not generated correctly.

## Swagger specification

Relevant schema snippet:

```
"post": {
                "operationId": "invitation_invite",
                "parameters": [
                    {
                        "name": "body",
                        "in": "body",
                        "description": "Email to invite",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "uniqueItems": true,
                            "items": {
                                "type": "object",
                                "required": [
                                    "email"
                                ],
                                "properties": {
                                    "email": {
                                        "type": "string"
                                    }
                                }
                            }
                        }
                    }
                ],
```
## Steps to reproduce

When building I get the following error:
```[...]/restapi/operations/invitation_invite_parameters.go:48: undefined: InvitationInviteParamsBodyItems0```

**Comment by casualjim** [comment] 2016-12-29 17:41
duplicate of: #733

**Comment by casualjim** [comment] 2016-12-29 17:41
fwiw I'm actually working on a  fix for this atm

**Closed by casualjim** 2016-12-29 17:41 UTC

**Comment by emsa23** [comment] 2016-12-29 17:54
I have a few deep structure under _definitions_ that works just fine, I've only seen this when declared directly in the operation.
