### ISSUE TITLE
v0.25.0 generates incorrect imports

### ISSUE THREAD

**Issue by hhubris** [go-swagger/go-swagger#2362] opened 2020-07-22 15:17 UTC
## Problem statement

swagger generate server --spec spec/swagger.yaml --target internal --model-package restapi/models

Using v.024.0 this generates responses with proper imports:

	"github.com/foo/bar/internal/restapi/models"

Using v0.25.0 restapi is missing, so the code won't compile

	"github.com/foo/bar/internal/models"

## Swagger specification
```yaml
swagger: '2.0'
info:
  title: Foo Bar
  version: "1.0"
  description: Temp description
schemes:
  - http
basePath: /api
produces:
  - application/json
  - text/plain
consumes:
  - application/json

paths:
  '/ping':
    get:
      summary: Ping the server
      description: Ping the server
      operationId: ping
      produces:
        - text/plain
      security: []
      responses:
        200:
          description: OK
          schema:
            type: string
            example:
              'pong'
        500:
          $ref: "#/responses/internalServerError"

definitions:
  Error:
    type: object
    properties:
      code:
        type: integer
      description:
        type: string

responses:
  internalServerError:
    description: Server error
    schema:
      $ref: '#/definitions/Error'
```

## Steps to reproduce
```bash
go mod init github.com/foo/bar
swagger generate server --spec spec/swagger.yaml --target internal --model-package restapi/models
go build ./...
```

## Environment
swagger version: 0.25.0
go version: 1.14.4
OS:   alpine (docker)

**Comment by hgedia** [comment] 2020-07-23 09:07
Most likely related , but  the same build/compilation of above api spec gives me the following error
```restapi/operations/app_api.go:275:19: o.context.APIHandlerSwaggerUI undefined (type *middleware.Context has no field or method APIHandlerSwaggerUI)
```

**Comment by fredbi** [comment] 2020-07-24 06:15
@hgedia I've just tried your use case (without the go.mod) and it generates the expected imports.
```
swagger generate server --spec fixture-2362.yaml --target internal --model-package restapi/model

grep 'models"' internal/restapi/operations/*.go
internal/restapi/operations/ping_responses.go:	"github.com/go-swagger/go-swagger/fixtures/bugs/2362/internal/restapi

go build ./internal/cmd/foo-bar-server
echo $?
0
```

Still trying to figure out how I can reproduce your issue...

**Comment by fredbi** [comment] 2020-07-24 06:18
Doing the same with an initialized module, and this still works ok for me.
```
go mod init github.com/go-swagger/go-swagger/fixtures/bugs/2362
swagger generate ...

grep 'models"' internal/restapi/operations/*.go
internal/restapi/operations/ping_responses.go:	"github.com/go-swagger/go-swagger/fixtures/bugs/2362/internal/restapi

go build ...
echo  $?
0
```

I am using: 
```
go version
go version go1.14.4 linux/amd64
```

**Comment by hhubris** [comment] 2020-07-24 16:22
I spent quite a bit of time trying to replicate this today, and I finally did.  I'm not sure what the root cause is, but can you try this shell script.  When I run this, I end up with the incorrect import here:

```head -20 internal/restapi/operations/ping_responses.go
// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/foo/bar/internal/models"
)

// PingOKCode is the HTTP code returned for type PingOK
const PingOKCode int = 200

/*PingOK OK```

This is the script I used to build.

```#!/usr/bin/env sh

rm -rf internal/restapi/models
rm -rf internal/restapi/operations

swagger generate server \
  --spec spec/swagger.yaml \
  --target internal \
  --model-package restapi/models \
  --principal models.Principal \
  --exclude-main \
  --name data-updater```

**Comment by fredbi** [comment] 2020-07-24 16:29
ok the problem comes from the use of the principal, which I have slightly changed after v0.24.0 (to fix some other issues with it). Let's see in details how it goes.

**Comment by fredbi** [comment] 2020-07-24 16:30
specifying the principal with a fully qualified package does the job, e.g.:
```
swagger generate server \
  --spec fixture-2362.yaml \
  --target internal \
  --model-package restapi/models \
  --principal github.com/go-swagger/go-swagger/fixtures/bugs/2362/internal/restapi/models.Principal \
  --exclude-main \
  --name data-updater
```

**Comment by fredbi** [comment] 2020-07-24 16:40
The change is due to https://github.com/go-swagger/go-swagger/pull/2325
The problem fixed by that one is when the principal is retrieved from some package outside the generated tree.

However, it looks that this fix overlooked the case of the "models" package, which generates a conflicting import.

**Comment by hhubris** [comment] 2020-07-24 16:43
Your suggested fix does work, and after updating all of the openapi dependencies, the code builds cleanly.

Is this fix backwards compatible?  Specifically if someone on the team rebuilds w/ v0.24.0 will it work?  Or should I revert the change and wait for v0.25.1?

Thanks for your help

**Comment by fredbi** [comment] 2020-07-24 17:13
There is nothing new to be expected on that >v0.25.0.

Specifically, even though we could make the package guess logic even smarter, this would be an enhancement, not a priority.

I think that specifying the principal with a full package would work in v0.24.0 just as well. I haven't checked, though.

**Comment by fredbi** [comment] 2020-07-25 05:01
@hhubris reconsidering a bit your use case. I believe it is rather common to do something like this, so the change brought by v0.25.0 about how to specify the package where to find principal is somehow breaking older habits. I'll try to enhance this so we get a smarter package resolution.

**Comment by GoDieNow** [comment] 2020-07-29 09:41
@fredbi when the generate server uses --template=stratoscale you get the error that @hgedia mentions

**Comment by tsorya** [comment] 2020-08-02 18:46
same here. using --template get the same error

**Comment by t-sin** [comment] 2020-11-11 02:29
FYI.

I met same problem with ` o.context.APIHandlerSwaggerUI undefined` and found this method defined in [here](https://github.com/go-openapi/runtime/blob/5fc6d7931327cf2e35c6f68b24964af682789b15/middleware/context.go). Because of checking my `go.mod`, my go-openapi/runtime is v0.19.15 but latest is 0.9.23. In my case, the problem was resolved with upgrading go-openapi/runtime.

**Closed** 2020-11-24 00:01 UTC
Labels: enhancement, generator, pending PR
