### ISSUE TITLE
Generating code for go modules is much slower than under GOPATH

### ISSUE THREAD

**Issue by nickform** [go-swagger/go-swagger#1826] opened 2018-11-30 15:10 UTC
## Problem statement

Generating server code for a Go module is much slower than doing so for the non-module equivalent.

## Swagger specification

Reproducible with [Petstore](https://petstore.swagger.io/) example.

## Steps to reproduce

1. In a directory outside of $GOPATH, download [petstore example swagger](https://petstore.swagger.io/v2/swagger.yaml) as swagger.yaml.
1. From that directory, run ```go mod init github.com/anything/whatever```.
1. Run ```swagger generate server -f .\swagger.yaml --name petstore```.
   1. Note time difference between first and last log entry timestamps.
1. Create a directory at $GOPATH/src/github.com/anything/whatever/petstore and copy the swagger.yaml (only) from step 1 there.
1. From that directory, run ```swagger generate server -f .\swagger.yaml --name petstore```.
   1. Note time difference between first and last log entry timestamp.

Difference for me

Step # | Measurement
------ | ----------------
3.i | 236 s 
5.i | 8 s 

Not that the go.mod does not at any point in the above steps list any requirements - its presence is enough to cause the substantial slowdown.

## Environment
swagger version: 0.17.2
go version: x.x.x  go version go1.11 windows/amd64
OS:   Windows 10

The slowdown has been observed to be even worse when running under docker.

**Comment by casualjim** [comment] 2018-11-30 16:43
That's not our bug :). Go modules are experimental in go, the go toolchain doesn't fully support them yet, and we're beholden to that toolchain. It's tracked here: https://github.com/golang/go/issues/24661

The assumption is that goimports (which we use for formatting and optimizing imports in codegen), resolves imports, and now go get goes out and pings repos for updates and so on every single time.

**Comment by nickform** [comment] 2018-11-30 17:22
Thanks for the response @casualjim.

It seems like the call to goimports is being made per generated file (or something approximating that cardinality). Could this not be done in a single step at the end?

**Comment by casualjim** [comment] 2018-11-30 17:35
unfortunately batching it would not reduce the amount of calls because it would still need to visit every file.

**Comment by bvwells** [comment] 2018-11-30 20:07
Looks like this is the issue tracking the performance of goimports:
https://github.com/golang/go/issues/27287

@casualjim - I saw in the code that there is an option to skip formatting of the code with goimports. How is this activated?

**Comment by fredbi** [comment] 2018-11-30 20:44
@bvwells  it is in the swagger.yaml config file.

**Comment by nickform** [comment] 2018-12-03 12:47
Thanks for the responses.

Since we're building in docker, we  have been able to avoid this problem by mounting the source directory into ```$GOPATH/src/<module-name>``` inside the container and then forcing modules off with ```GO111MODULE=off```. This gives the correct local imports and the better performance. This workaround won't be available to everyone but I'm happy for this issue to be closed.

While I'm writing, thanks to all those who have contributed to the development and maintenance of this tool - it has saved countless hours of typing and has proved flexible enough for us to always do what we need to.

**Comment by denisvmedia** [comment] 2021-12-26 14:02
Is it still an issue? If so, is there any other workaround rather than switching off go mod?

**Comment by oliwer** [comment] 2022-08-22 12:57
@nickform Do you know if your workaround still works with go-swagger v0.29.0? Because I tried to reproduce it and setting `GO111MODULE=off` or not does not seem to have any impact.

**Comment by nickform** [comment] 2022-08-25 20:07
I have no idea I'm afraid - I no longer work on the project where I was using this tool. Sorry.

**Comment by casualjim** [comment] 2022-08-26 00:02
This is from 3 years ago, I'm going to close this ticket because now go modules are the default path in go.

**Closed by casualjim** 2022-08-26 00:02 UTC
Labels: dependency, go modules, goimport
