### ISSUE TITLE
Generated code contains type error

### ISSUE THREAD

**Issue by davidv1992** [go-swagger/go-swagger#2128] opened 2019-12-07 15:57 UTC
## Problem statement

When generating code for the eve esi api spec, generation completes succesfully, but the resulting code contains a type error in client/routes/get_route_origin_destination_parameters.go

## Swagger specification

https://esi.evetech.net/_latest/swagger.json

relevant section seems to be

        "/v1/route/{origin}/{destination}/":{
            "get":{
                "description":"Get the systems between origin and destination\n\n---\n\nThis route is cached for up to 86400 seconds",
                "operationId":"get_route_origin_destination",
                "parameters":[
                    {
                        "description":"avoid solar system ID(s)",
                        "in":"query",
                        "items":{
                            "format":"int32",
                            "type":"integer"
                        },
                        "maxItems":100,
                        "name":"avoid",
                        "type":"array",
                        "uniqueItems":true
                    },
                    {
                        "description":"connected solar system pairs",
                        "in":"query",
                        "items":{
                            "collectionFormat":"pipes",
                            "items":{
                                "format":"int32",
                                "type":"integer"
                            },
                            "maxItems":2,
                            "minItems":2,
                            "type":"array",
                            "uniqueItems":true
                        },
                        "maxItems":100,
                        "name":"connections",
                        "type":"array",
                        "uniqueItems":true
                    },
                    {
                        "$ref":"#/parameters/datasource"
                    },
                    {
                        "description":"destination solar system ID",
                        "format":"int32",
                        "in":"path",
                        "name":"destination",
                        "required":true,
                        "type":"integer"
                    },
                    {
                        "default":"shortest",
                        "description":"route security preference",
                        "enum":[
                            "shortest",
                            "secure",
                            "insecure"
                        ],
                        "in":"query",
                        "name":"flag",
                        "type":"string"
                    },
                    {
                        "$ref":"#/parameters/If-None-Match"
                    },
                    {
                        "description":"origin solar system ID",
                        "format":"int32",
                        "in":"path",
                        "name":"origin",
                        "required":true,
                        "type":"integer"
                    }
                ],
                "responses":{
                    "200":{
                        "description":"Solar systems in route from origin to destination",
                        "examples":{
                            "application/json":[
                                30002771,
                                30002770,
                                30002769,
                                30002772
                            ]
                        },
                        "headers":{
                            "Cache-Control":{
                                "description":"The caching mechanism used",
                                "type":"string"
                            },
                            "ETag":{
                                "description":"RFC7232 compliant entity tag",
                                "type":"string"
                            },
                            "Expires":{
                                "description":"RFC7231 formatted datetime string",
                                "type":"string"
                            },
                            "Last-Modified":{
                                "description":"RFC7231 formatted datetime string",
                                "type":"string"
                            }
                        },
                        "schema":{
                            "description":"Solar systems in route",
                            "items":{
                                "description":"Solar system in route",
                                "format":"int32",
                                "title":"Solar system ID",
                                "type":"integer"
                            },
                            "maxItems":1000,
                            "title":"get_route_origin_destination_ok",
                            "type":"array"
                        }
                    },
                    "304":{
                        "description":"Not modified",
                        "headers":{
                            "Cache-Control":{
                                "description":"The caching mechanism used",
                                "type":"string"
                            },
                            "ETag":{
                                "description":"RFC7232 compliant entity tag",
                                "type":"string"
                            },
                            "Expires":{
                                "description":"RFC7231 formatted datetime string",
                                "type":"string"
                            },
                            "Last-Modified":{
                                "description":"RFC7231 formatted datetime string",
                                "type":"string"
                            }
                        }
                    },
                    "400":{
                        "description":"Bad request",
                        "examples":{
                            "application/json":{
                                "error":"Bad request message"
                            }
                        },
                        "schema":{
                            "$ref":"#/definitions/bad_request"
                        }
                    },
                    "404":{
                        "description":"No route found",
                        "examples":{
                            "application/json":{
                                "error":"Not found message"
                            }
                        },
                        "schema":{
                            "description":"Not found",
                            "properties":{
                                "error":{
                                    "description":"Not found message",
                                    "title":"get_route_origin_destination_404_not_found",
                                    "type":"string"
                                }
                            },
                            "title":"get_route_origin_destination_not_found",
                            "type":"object"
                        }
                    },
                    "420":{
                        "description":"Error limited",
                        "examples":{
                            "application/json":{
                                "error":"Error limited message"
                            }
                        },
                        "schema":{
                            "$ref":"#/definitions/error_limited"
                        }
                    },
                    "500":{
                        "description":"Internal server error",
                        "examples":{
                            "application/json":{
                                "error":"Internal server error message"
                            }
                        },
                        "schema":{
                            "$ref":"#/definitions/internal_server_error"
                        }
                    },
                    "503":{
                        "description":"Service unavailable",
                        "examples":{
                            "application/json":{
                                "error":"Service unavailable message"
                            }
                        },
                        "schema":{
                            "$ref":"#/definitions/service_unavailable"
                        }
                    },
                    "504":{
                        "description":"Gateway timeout",
                        "examples":{
                            "application/json":{
                                "error":"Gateway timeout message"
                            }
                        },
                        "schema":{
                            "$ref":"#/definitions/gateway_timeout"
                        }
                    }
                },
                "summary":"Get route",
                "tags":[
                    "Routes"
                ],
                "x-alternate-versions":[
                    "dev",
                    "legacy",
                    "v1"
                ],
                "x-cached-seconds":86400
            }
        },

## Steps to reproduce

Run the following inside gopath somewhere:

swagger generate client -f https://esi.evetech.net/_latest/swagger.json
go get -v ./...

Second command will indicate syntax error

## Environment
swagger version: 2.1.0 (prebuilt), master (04b61d1)
go version: go1.11.4 linux/amd64  
OS:   ubuntu 18.04.3 lts

**Comment by fredbi** [comment] 2019-12-07 19:13
Yes I could reproduce your issue. This is a duplicate of #1505 with nested array query params. I have fixed this quite some time ago for the generated server, but unfortunately not for this client.

**Closed** 2021-01-16 19:56 UTC
Labels: bug, duplicate, generate client, pending PR
