### ISSUE TITLE
[Question] How to set cookies from server side

### ISSUE THREAD

**Issue by xuanzhaopeng** [go-swagger/go-swagger#728] opened 2016-11-08 00:05 UTC
## Problem statement

Hi ! I come back again since a long vocation! 

I have a simple question, how could we set cookies when I return the request ?

Solution (with corsHandler):
```go
func setupGlobalMiddleware(handler http.Handler) http.Handler {
	corsHandler := cors.New(cors.Options{
		Debug: false,
		AllowedHeaders:[]string{"*"},
		AllowedOrigins:[]string{"*"},
		AllowedMethods:[]string{},
		AllowCredentials: true,
		MaxAge:1000,
	})
	corsHandler.Log = zllogger.Trace
	h := corsHandler.Handler(handler)
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		expiration := time.Now().Add(365 * 24 * time.Hour)
		cookie  :=  http.Cookie{Name: "yoyo",Value:"abcd",Expires:expiration}
		http.SetCookie(w, &cookie)
		zllogger.Info.Println("set cookies done")
		h.ServeHTTP(w, r)
	})
}
```

Thanks
Robin

**Comment by casualjim** [comment] 2016-11-24 23:18
duplicate of #748

**Closed by casualjim** 2016-11-24 23:18 UTC
