### ISSUE TITLE
Can't reference definition from file in same directory

### ISSUE THREAD

**Issue by wittrock** [go-swagger/go-swagger#776] opened 2016-12-06 18:52 UTC
## Problem statement

I'm trying to split my definitions off from my main API so they can be used in another API as well.

According to https://github.com/go-swagger/go-swagger/issues/45, it looks like I should be able to do per-model references, as below. However, this doesn't work.

On both go-swagger versions 0.7.4 (latest release) and the HEAD of the master branch, I get an error parsing `error.yaml`.

The `d` the error message mentions is the front of the `definitions` key. If I change the leading letter, the error message changes as well.

It looks like https://github.com/go-openapi/spec/pull/15 fixed something related to this, but as above, I've tried master to no avail.

## Swagger specification

swagger-template.yaml:
```yaml
swagger: '2.0'
info:
  title: Test
  version: '1.0.0'
host: localhost
basePath: /
produces:
  - application/json
schemes:
  - http
paths:
  /healthy:
    get:
      responses:
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Error:
    $ref: ./error.yaml#/definitions/Error
``` 

error.yaml:
```yaml
definitions:
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
```

## Steps to reproduce

```sh
➜  swagger-test $ swagger generate server -f swagger-template.yaml
2016/12/06 13:43:14 building a plan for generation
2016/12/06 13:43:14 planning definitions
invalid character 'd' looking for beginning of value

➜  swagger-test $ swagger version
version: 0.7.4
commit: 6b8226461ff1d53e4b56ea0ea80d126aa3e9d7b5


➜  swagger-test $ /Users/johnwittrock/src/go/bin/swagger generate server -f swagger-template.yaml
2016/12/06 13:45:16 building a plan for generation
2016/12/06 13:45:16 planning definitions
invalid character 'd' looking for beginning of value

➜  swagger-test $ /Users/johnwittrock/src/go/bin/swagger version         dev
```

**Comment by jbub** [comment] 2016-12-06 18:55
Probably duplicate of #729

**Closed** 2016-12-26 08:11 UTC
Labels: bug
