### ISSUE TITLE
Unmarshal error returned without further context

### ISSUE THREAD

**Issue by wlcx** [go-swagger/go-swagger#77] opened 2015-10-22 21:00 UTC
Running `swagger generate client` on a spec which has passed `swagger validate` (At least, the command exited with no errors/output....) is resulting in the following: 
```
$ swagger generate client -f swagger.json
json: cannot unmarshal bool into Go value of type string
```

Is there an easy way to see where this has been generated to work out what the problem is?

**Comment by casualjim** [comment] 2015-10-23 03:08
would it be possible to show me the spec?

**Comment by casualjim** [comment] 2015-11-13 19:17
this might be because of lack of a space between the colon after a key and the value

results in the error:
```yaml
definitions:
  error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type:string
```


correct: 
```yaml
definitions:
  error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
```

**Comment by casualjim** [comment] 2016-02-15 02:23
considering there was no answer for this long, I'm going to close this and assume there was a resolution.

**Closed by casualjim** 2016-02-15 02:23 UTC
Labels: needs more info

**Comment by johndunne** [comment] 2017-02-02 18:49
Pardon my reopening an old issue! I've encountered this exact same problem. I'm getting the error message
`2017/02/02 18:38:54 json: cannot unmarshal bool into Go value of type []string`
and I've no idea what in the 5824 line yaml file is causing the error. Some debug output identifying approximately where go-swagger got to when the issue is encountered would be great.

**Comment by casualjim** [comment] 2017-02-02 18:50
run the generation process with: DEBUG=1 SWAGGER_DEBUG=1

**Comment by casualjim** [comment] 2017-02-02 18:53
the problem with line numbers and so on is not the problem in go-swagger it's with the stdlib json and go-yaml implementations.
if you're able to share the spec I may be able to help you out but for now we have no control over linenumbers and character positions because we are reliant on the way go's stdlib json library works. I'm open to any suggestions on making this better because I know it's a problem

**Comment by johndunne** [comment] 2017-02-02 19:10
Hi, thanks your help! I've actually found the issue by diffing the last commit. The problem was a definitions object which looked like this:
`definitions:
  MenuItem:
    properties:
      group_id:
        type: integer
        format: int64
      item_position:
        type: integer
        format: int32
      item_currency:
        type: string
        required: false`
where the item_currency's required key is false. I think go-swagger was expecting a []string here and not a boolean.

**Comment by evalevanto** [comment] 2019-04-17 15:06
Hello, I am facing a similar issue. 

`operation (CreateIssueRequest): no spec available to unmarshal`

on running with this: 
> run the generation process with: DEBUG=1 SWAGGER_DEBUG=1

here is the output:
`inferring for string with models at github.com/Evalyn-Kemunto/token-api/vendor/github.com/hyperledger/fabric-sdk-go/pkg/fab/events/service/dispatcher against github.com/Evalyn-Kemunto/token-api/models
2019/04/17 18:02:42 inferring for string with models at github.com/Evalyn-Kemunto/token-api/vendor/github.com/go-logfmt/logfmt against github.com/Evalyn-Kemunto/token-api/models
2019/04/17 18:02:42 inferring for string with models at vendor/golang_org/x/crypto/cryptobyte/asn1 against github.com/Evalyn-Kemunto/token-api/models
2019/04/17 18:02:42 inferring for string with models at github.com/Evalyn-Kemunto/token-api/vendor/golang.org/x/net/context against github.com/Evalyn-Kemunto/token-api/models
2019/04/17 18:02:42 inferring for string with models at github.com/Evalyn-Kemunto/token-api/vendor/google.golang.org/grpc/peer against github.com/Evalyn-Kemunto/token-api/models
2019/04/17 18:02:42 inferring for string with models at github.com/Evalyn-Kemunto/token-api/vendor/google.golang.org/grpc/connectivity against github.com/Evalyn-Kemunto/token-api/models
2019/04/17 18:02:42 inferring for string with models at github.com/Evalyn-Kemunto/token-api/vendor/google.golang.org/grpc/resolver against github.com/Evalyn-Kemunto/token-api/models
2019/04/17 18:02:42 inferring for string with models at github.com/Evalyn-Kemunto/token-api/vendor/golang.org/x/sys/unix against github.com/Evalyn-Kemunto/token-api/models
2019/04/17 18:02:42 inferring for string with models at github.com/Evalyn-Kemunto/token-api/vendor/github.com/prometheus/common/internal/bitbucket.org/ww/goautoneg against github.com/Evalyn-Kemunto/token-api/models
2019/04/17 18:02:42 inferring for string with models at github.com/Evalyn-Kemunto/token-api/vendor/github.com/hyperledger/fabric-sdk-go/pkg/fab/events/deliverclient/seek against github.com/Evalyn-Kemunto/token-api/models
2019/04/17 18:02:42 inferring for string with models at encoding/xml against github.com/Evalyn-Kemunto/token-api/models
2019/04/17 18:02:42 inferring for string with models at github.com/Evalyn-Kemunto/token-api/vendor/github.com/hyperledger/fabric-sdk-go/pkg/fab/events/service against github.com/Evalyn-Kemunto/token-api/models
2019/04/17 18:02:42 inferring for string with models at github.com/Evalyn-Kemunto/token-api/vendor/golang.org/x/crypto/pkcs12/internal/rc2 against github.com/Evalyn-Kemunto/token-api/models
2019/04/17 18:02:42 inferring for string with models at github.com/Evalyn-Kemunto/token-api/vendor/github.com/hashicorp/hcl/json/token against github.com/Evalyn-Kemunto/token-api/models
2019/04/17 18:02:42 inferring for string with models at github.com/Evalyn-Kemunto/token-api/vendor/golang.org/x/text/width against github.com/Evalyn-Kemunto/token-api/models
2019/04/17 18:02:42 inferring for string with models at runtime/debug against github.com/Evalyn-Kemunto/token-api/models
2019/04/17 18:02:42 inferring for string with models at github.com/Evalyn-Kemunto/token-api/vendor/github.com/hyperledger/fabric-sdk-go/pkg/common/providers/core against github.com/Evalyn-Kemunto/token-api/models
2019/04/17 18:02:42 inferring for string with models at crypto/sha256 against github.com/Evalyn-Kemunto/token-api/models
2019/04/17 18:02:42 inferring for string with models at github.com/Evalyn-Kemunto/token-api/vendor/golang.org/x/crypto/sha3 against github.com/Evalyn-Kemunto/token-api/models
2019/04/17 18:02:42 inferring for string with models at github.com/Evalyn-Kemunto/token-api/vendor/github.com/google/certificate-transparency-go/x509 against github.com/Evalyn-Kemunto/token-api/models
2019/04/17 18:02:42 inferring for string with models at github.com/Evalyn-Kemunto/token-api/models against github.com/Evalyn-Kemunto/token-api/models`

**Comment by casualjim** [comment] 2019-04-17 15:51
required is not a boolean in json schema, it shouldn't have passed validation
