### ISSUE TITLE
Pass http.Request instance to user's HttpAuthenicator

### ISSUE THREAD

**Issue by dreamlover** [go-swagger/go-swagger#1043] opened 2017-05-16 02:53 UTC
## Problem statement
Currently, the user's TokenAuthentication func only got the token string passed.
```
// TokenAuthentication authentication function
type TokenAuthentication func(string) (interface{}, error)
```
Sometimes it's not enough to verify the token string when it's calculated based on info like the query path or body data, which should be fetched through the http.Request interface. So is it possible to pass the http.Request instance to the auth func?
```
// TokenAuthWithRequest authentication function
type TokenAuthWithRequest func(string, *http.Request) (interface{}, error)
```

**Comment by casualjim** [comment] 2017-05-17 04:09
duplicate of #1040

**Closed by casualjim** 2017-05-17 04:09 UTC
Labels: duplicate
