### ISSUE TITLE
How to use swagger UI?

### ISSUE THREAD

**Issue by joeblew99** [go-swagger/go-swagger#542] opened 2016-05-27 14:21 UTC
## Problem statement

I cant get the swagger-ui to run in the browser. 
In the browser http://127.0.0.1:53536/swagger-ui/ gets me:
````
This page contains the following errors:

error on line 1 at column 1: Document is empty
Below is a rendering of the page up to the first error.

`````

i am using the petsotre example. I pulled the code yesterday so its fresh.

On my terminal i have the following:
`````

 # Validate
 swagger validate ./swagger.json
 
# Delete old
 rm -rf cmd
 rm -rf cmd
 rm -rf models
 rm -rf restapi
 
 # Gen 
 #swagger generate server -A IssueTracker -f ./swagger.yml
 swagger generate server -A PetStore -f ./swagger.json
 
 swagger generate client -A PetStore -f ./swagger.json

go build cmd/pet-store-server/main.go

./main

2016/05/27 15:58:30 Serving pet store at http://127.0.0.1:53536

**Comment by joeblew99** [comment] 2016-05-27 14:28
http://127.0.0.1:3000/swagger.json works, returning the json file.

http://127.0.0.1:3000 returns the same error message of:
````
{"code":404,"message":"path / was not found"}
````

**Comment by casualjim** [comment] 2016-05-27 14:40
I don't quite understand the problem yet.The error message comes when you try to call the petstore api or when you try to load the swagger ui?
You're using the swagger ui docker container? 
Did you add a CORS middleware to your swagger server?

**Comment by joeblew99** [comment] 2016-05-27 17:47
How to enable cors ? That's the likely culprit.
I could not fing it anywhere

**Comment by casualjim** [comment] 2016-05-27 17:54
https://github.com/rs/cors
http://goswagger.io/use/middleware/

**Comment by themalkolm** [comment] 2016-08-31 11:16
@joeblew99 you probably already figured it out. To help other googlers: *don't* forget to add `/v1` prefix or or whatever you have specified in `basePath`.

**Comment by casualjim** [comment] 2016-09-03 23:47
duplicate of #481

**Closed by casualjim** 2016-09-03 23:47 UTC
Labels: duplicate, question
