### ISSUE TITLE
Go-swagger validation issues

### ISSUE THREAD

**Issue by lixingwang** [go-swagger/go-swagger#61] opened 2015-09-21 08:06 UTC
There are 3 issues that I found.

For the test swagger file, you can download from: https://github.com/lixingwang/go-swagger-files/blob/master/SwaggerValidationIssues.json

1. Validation error while define parameter with more than one ref fields(line 319).
![1](https://cloud.githubusercontent.com/assets/987686/9987389/24bd179a-607a-11e5-96bb-36072d324a0d.png)
2. Validate Error while define response definition and including 'examples' element(line 847)

![2](https://cloud.githubusercontent.com/assets/987686/9987390/24bd7be0-607a-11e5-9c3a-e0c6f333a764.png)
3. Validate Error while define parameter definition and including path parameter element(line 30 and line 804)
![3](https://cloud.githubusercontent.com/assets/987686/9987391/24bfdb60-607a-11e5-9e87-372773e42767.png)

They should valid swagger file but go-swagger validator treat it as invalid.

**Comment by dolmen** [comment] 2015-09-30 09:45
3 different issues should be filled a 3 different tickets.

**Comment by casualjim** [comment] 2015-10-17 03:55
duplicate of issue #16 
duplicate of issue #18 

the invalid example is a valid issue, ideally this would have just contained that one issue as the other ones are already known

**Closed** 2015-10-30 19:04 UTC
Labels: bug
