### ISSUE TITLE
External $refs and polymorphism: models for subtypes not generated

### ISSUE THREAD

**Issue by llorllale** [go-swagger/go-swagger#1885] opened 2019-02-22 15:14 UTC
## Problem statement
Models not generated for subtypes of a type when both defined in external `$ref`.
## Swagger specification
In this example, `WriteRequest` will not be generated.

`swagger.yaml`:
```yaml
...
paths:
  /collections:
    post:
      ...
      parameters:
        - name: serverRequest
          shema:
            $ref: 'collections.yaml/#BaseRequest' 
```
`collections.yaml`
```yaml
BaseRequest:
  type: object
  discriminator: '@type'
  properties:
    '@type':
       type: string
    ...
WriteRequest:
  type: object
  allOf:
    - $ref: '#BaseRequest'
    - properties:
          ...
```
## Steps to reproduce
Take something similar to the examples above and just do `swagger generate server --spec=swagger.yaml`. The model for `BaseRequest` will be present, but not for `WriteRequest`.
## Environment
swagger version: `0.18.0`
go version: `1.11.4` 
OS: `Ubuntu 18.04`

**Comment by fredbi** [comment] 2019-02-22 15:28
The ref with only a fragment is invalid. Try: `$ref: "#/BaseRequest` instead

**Comment by llorllale** [comment] 2019-02-22 16:13
@fredbi doesn't work either.

Here are test specs (only `WriteRequest` ends up missing):

`swagger.yaml`
```yaml
swagger: '2.0'
info:
  version: 0.1.0
  title: test
  description: test
paths:
  /collections:
    post:
      produces:
        - application/jose
        - application/json
      description: 'test'
      parameters:
        - name: serverRequest
          in: body
          required: true
          schema:
            $ref: 'collections.yaml#/BaseRequest'
      responses:
        '200':
          description: 'test'
          schema:
            $ref: 'collections.yaml#/Response'
```
`collections.yaml`
```yaml
BaseRequest:
  type: object
  discriminator: '@type'
  properties:
    '@type':
       type: string
WriteRequest:
  type: object
  allOf:
    - $ref: '#/BaseRequest'
    - properties:
        test:
          type: string
Response:
  type: object
  properties:
    test:
      type: string
```

**Comment by fredbi** [comment] 2019-02-22 17:49
Ok now I understand what is happening.
Since there is no reference from the spec to the `WriteRequest` it is not pulled by the spec flattening (you can see the same result with just `swagger flatten {your spec}`.

That's because the flattening only pulls dependencies based on `$ref`, and not based on the implicit dependency created by the subtype definition.

If you add to your spec an entry point that pulls the `WriteRequest` then everything goes as expected.

I don't think we can reasonably fix this issue in flatten, since this would force the process to explore the rabbit hole and figure out afterwards if any such implicit dependency exist.

**Comment by llorllale** [comment] 2019-02-22 19:13
@fredbi yup, I was afraid that'd be the assessment.

What should we do with this issue then? Is it a "won't fix"? Do we have a list of known issues somewhere?

**Comment by fredbi** [comment] 2019-02-22 19:19
Just query open issues with appropriate filter. Tags are rather well maintained.

**Comment by fredbi** [comment] 2019-02-22 19:23
I don't it is a "won't fix"... I would say: "sure, I won't fix it". This could be an enhancement, though, but I doubt any candidate will be ready to pay the price to bring a real fix for this in flatten. 

If you feel strong about it, you can have a look at the flatten code here https://github.com/go-openapi/analysis

**Comment by fredbi** [comment] 2019-10-19 21:47
@llorllale I've recently made some change to the spec flattening logics (in latest release), due to errors when walking the ref tree, which might match you expectations. The $ref tree is now explored in full.

You'd probably give it a shot for your use case.

**Comment by fredbi** [comment] 2023-12-20 20:25
Looking back at this long standing issue, namely not exploring the full tree of possible subtypes in all possible remote documents... Definitely won't fix.

There is an easy work around, though: referencing subtypes with a dummy definition then flatten using "remove-unused".


Example:
```yaml
swagger: '2.0'
info:
  version: 0.1.0
  title: test
  description: test
paths:
  /collections:
    post:
      produces:
        - application/json
      description: 'test'
      parameters:
        - name: serverRequest
          in: body
          required: true
          schema:
            $ref: 'collections.yaml#/BaseRequest'
      responses:
        '200':
          description: 'test'
          schema:
            $ref: 'collections.yaml#/Response'
definitions:
  dummy:
    $ref: 'collections.yaml#/WriteRequest'
```

Flattening the spec like so:  swagger flatten swagger.yaml --with-flatten=remove-unused --format=yaml
yields something like the OP wanted:
```yaml
swagger: "2.0"
info:
    description: test
    title: test
    version: 0.1.0
paths:
    /collections:
        post:
            produces:
                - application/json
            parameters:
                - name: serverRequest
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/baseRequest'
            responses:
                "200":
                    schema:
                        $ref: '#/definitions/response'
                    description: test
            description: test
definitions:
    baseRequest:
        type: object
        properties:
            '@type':
                type: string
        discriminator: '@type'
    response:
        properties:
            test:
                type: string
        type: object
    writeRequest:
        type: object
        allOf:
            - $ref: '#/definitions/baseRequest'
            - properties:
                test:
                    type: string
```

**Comment by fredbi** [comment] 2023-12-20 20:26
Closing: the problem is hard to solve, with complex ramifications, possibly unwantd ones.
On the other hand, a straightforward workaround is available.

**Closed by fredbi** 2023-12-20 20:26 UTC
Labels: enhancement, Ref resolution, flatten, discriminator
