### ISSUE TITLE
invalid client code generated for spec

### ISSUE THREAD

**Issue by remster** [go-swagger/go-swagger#1770] opened 2018-10-24 14:50 UTC
## Problem statement
This does not happen for every spec, but one i list is affected. The client code contains an illegal import statement:
```
cat ./client/metastore_client.go 
```
```Go

// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/redacted/client/metadata"

	"github.com/redacted/client/metadata" <---- HERE double import
)

// Default metastore HTTP client.
var Default = NewHTTPClient(nil)
```
## Swagger specification
```yaml
swagger: "2.0"
info:
  description: "Metadata store"
  version: 1.0.0
  title: Metastore
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
tags:
  - name: index
    description: Main entry
    externalDocs:
      description: Find out more
      url: "http://swagger.io"
schemes:
  - http
paths:
  /index/mission:
    put:
      tags:
        - metadata
      summary: Update mission info
      description: ""
      operationId: updateMission
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Mission info
          required: true
          schema:
            required:
            - applyTo
            - document
            properties:
              applyTo:
                type: object
                properties:
                  name:
                    type: string
              document:
                type: object
                properties:
                  name:
                    type: string
      responses:
        200:
          description: ""
          schema:
            type: object
            properties:
              name:
                type: string
        default:
          description: error
          schema:
            type: object
            properties:
              name:
                type: string
```
## Steps to reproduce
`swagger generate client -f ./swagger.yaml -t .`
## Environment
swagger version: dev
go version: 1.11 
OS:  Ubuntu 18.04

**Comment by blancharda** [comment] 2018-10-24 17:43
I am experiencing the same issue with my own specs.
The problem seems tied to the version update from v0.17.0 -> v0.17.1.

**Comment by casualjim** [comment] 2018-10-24 18:03
this is fixed now on master

**Closed by casualjim** 2018-10-24 18:03 UTC

**Comment by casualjim** [comment] 2018-10-24 18:17
we use goimports, I updated that dependency again. 

I can't reproduce the issue with the spec in this issue. If this isn't fixed I can reopen

I've tried on a mac and in a golang:alpine container

**Comment by blancharda** [comment] 2018-10-24 18:57
I can't speak for @remster - but it looks like my particular error cases have been resolved :+1:. 

Thanks!

**Comment by remster** [comment] 2018-10-24 19:49
It is fixed for @remster too. Thank you for the quick action
