### ISSUE TITLE
generate spec for embedded struct: unknown primitive 

### ISSUE THREAD

**Issue by danfang** [go-swagger/go-swagger#241] opened 2016-01-29 07:40 UTC
The spec generate will often fail for me given the following definitions (for example)

``` go
// ActionParam
//
// swagger:parameters actionParam
type ActionParam struct {
    // in: body
    // required: true
    Body actionParam
}

type actionParam struct {
    // required: true
    FieldA string

    // required: true
    FieldB string

    // required: true
    FieldC int`
}
```

Generating a spec for this file will yield: `unknown primitive "actionParam"`
Changing around all the fields, names, etc does not fix the issue.

Currently on go 1.5.2 darwin/amd64 with the latest version of swagger.

**Comment by casualjim** [comment] 2016-02-07 22:45
I have a hard time reproducing this. When I include the file in my test application it just passes

**Comment by danfang** [comment] 2016-02-08 01:36
Yes, it seems like a flaky issue - I might try running the tool on another machine or platform, but it seems doubtful that that would fix the issue. Some more information about the project: 
- there are many different packages in the project that depend on each other (the issues appeared in sub-sub packages from the root, but this is probably more correlation than causation)
- the problem will often go away when moving the struct declarations to another file in the same package but sometimes not
- in a previous version of go-swagger, the error would read `unknown primitive "error"`

I've since moved all of the swagger comments from the project and will define everything in a .yml instead.

**Comment by casualjim** [comment] 2016-02-08 01:40
out of curiosity, when it fails did the project compile?

**Comment by danfang** [comment] 2016-02-08 01:41
yep!

**Comment by alioygur** [comment] 2016-02-16 16:39
+1

**Comment by casualjim** [comment] 2016-02-16 16:58
I understand this issue exists, but I have trouble reproducing it. So if you do have this issue and you can provide me steps on how to reproduce it, that would be greatly appreciated. 

I can try to fix what I can't reproduce, because I won't know if it's really fixed so it becomes a bit like shrodingers cat.

**Comment by alioygur** [comment] 2016-02-16 17:02
@casualjim I am new on Golang.

there is my file called as response.go
```go
package app

import (
	"github.com/alioygur/piklook-corporate/app/domain"
	"github.com/alioygur/piklook-corporate/app/lib"
)

type times struct {
	CreatedAt int64 `json:"createdAt"`
	UpdatedAt int64 `json:"updatedAt"`
}

type response struct {
	Data interface{} `json:"data"`
}

type userRes struct {
	ID       int64  `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
	times
}

func newUserRes(user *domain.User) *userRes {
	res := new(userRes)
	lib.CopyTo(user, res)

	return res
}

// swagger:response jobRes
type jobRes struct {
	ID          int64       `json:"id"`
	UserID      int64       `json:"userId"`
	Title       string      `json:"title"`
	Description string      `json:"description"`
	Skills      []*skillRes `json:"skills,omitempty"`
}

type skillRes struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func newJobRes(job *domain.Job) interface{} {
	res := new(jobRes)

	lib.CopyTo(job, res)

	skillRess := make([]*skillRes, len(job.Skills))

	for i, skill := range job.Skills {
		lib.CopyTo(skill, &skillRess[i])
	}

	res.Skills = skillRess

	return response{res}
}

func newJobsRes(jobs []*domain.Job) interface{} {
	res := make([]jobRes, len(jobs))
	for index, p := range jobs {
		lib.CopyTo(p, &res[index])
	}

	return response{res}
}
```

The error

```sh
➜  piklook-corporate  swagger generate spec -o swagger.json
unknown field type ele for "skills"
```

**Comment by fsouza** [comment] 2016-03-02 18:18
Hey there, I'm fighting this issue and managed to track it down to an interface. I have the following interface:

```go
// TranscodingProvider represents a provider of transcoding.
//
// It defines a basic API for transcoding a media and query the status of a
// Job. The underlying provider should handle the profileSpec as deisired (it
// might be a JSON, or an XML, or anything else.
type TranscodingProvider interface {
	JobStatus(id string) (*JobStatus, error)

	// Healthcheck should return nil if the provider is currently available
	// for transcoding videos, otherwise it should return an error
	// explaining what's going on.
	Healthcheck() error
}
```

There's no special mark-up in this interface. It considers the Healthcheck method to be an attribute. If I remove the method, it works. If I change ``swaggerSchemaForType`` (in go-swagger code) to treat an error as a string ([see the diff](https://gist.github.com/fsouza/fc7e6d58c6e804069dd3)), it includes TranscodingProvider as one of the definitions in the manifest, declaring it as follow:

```json
  "TranscodingProvider": {
      "description": "It defines a basic API for transcoding a media and query the status of a\nJob. The underlying provider should handle the profileSpec as deisired (it\nmight be a JSON, or an XML, or anything else.",
      "type": "object",
      "title": "TranscodingProvider represents a provider of transcoding.",
      "properties": {
        "Healthcheck": {
          "description": "Healthcheck should return nil if the provider is currently available\nfor transcoding videos, otherwise it should return an error\nexplaining what's going on.",
          "type": "string"
        }
      },
      "x-go-package": "github.com/nytm/video-transcoding-api/provider"
    }
```
```

**Comment by casualjim** [comment] 2016-03-02 18:33
if you can add this as a test and PR that'd be great

**Comment by fsouza** [comment] 2016-03-02 18:51
@casualjim I can, but what's the right fix? Ignore interfaces?

**Comment by casualjim** [comment] 2016-03-02 18:57
I think treating error as string, that worked for you right.
I don't think it will fix the issue completely but it definitely fixes some cases

**Comment by fsouza** [comment] 2016-03-02 19:08
But don't you think that treating an interface method as a property is buggy? Interfaces have no properties, they should be skipped.

**Comment by casualjim** [comment] 2016-03-02 19:51
it is used for the allOf case and discriminators.
it only considers methods with no args and a single return argument.

**Comment by fsouza** [comment] 2016-03-02 19:54
I see. Can I have a ``swagger:skip`` or something like that then? It's really a method that takes no arguments and returns a single parameter, it is not an accessor.

**Comment by casualjim** [comment] 2016-03-02 19:56
that's a great idea

**Comment by fsouza** [comment] 2016-03-02 20:16
@casualjim I think it's more complicated. Anyway, I sent PR #349 treating error as strings, I'm not sure if it's fine to change the fixture, please let me know what you think.

**Comment by abclogin** [comment] 2016-03-02 22:11
> Generating a spec for this file will yield: unknown primitive "actionParam"


I confirm. I found a similar error: unknown primitive "MyTypeName".


And this error is **random**.


I traced the error.


func findSourceFile (pkg * loader.PackageInfo, typeName string) to scan / schema.go file, line 760
This function not found information sometimes.


I traced next.


The fact is that sometimes loader.PackageInfo not contain all the information.
Thus we have the error is in the direction golang.org/x/tools/go/loader

**Comment by casualjim** [comment] 2016-03-02 22:15
wonderful, thanks so much for doing this

**Comment by abclogin** [comment] 2016-03-02 23:19
I was fool this bug.
I was rename my package "myPackagePath/errors" to "myPackagePath/apierrors".
go-swagger works fine after.

But this bug exists.

**Comment by gaplyk** [comment] 2016-03-07 19:35
Faced same issue: 
after 2 days investigation got  the place where it's failing:
https://github.com/go-swagger/go-swagger/blob/master/scan/schema.go#L745
because 
*ast.InterfaceType not found it this case structure. I could not reproduce this error without the code, but it the code it's failing always.

**Comment by fsouza** [comment] 2016-05-31 20:53
I'm facing this issue one more time, this time intermittently. I didn't investigate it much further, but could ``swaggerSchemaForType`` ignore unknown primitives? I mean, apply this patch:

```diff
diff --git a/scan/scanner.go b/scan/scanner.go
index d8053c4..9a78197 100644
--- a/scan/scanner.go
+++ b/scan/scanner.go
@@ -408,8 +408,6 @@ func swaggerSchemaForType(typeName string, prop swaggerTypable) error {
                prop.Typed("number", "float")
        case "float64":
                prop.Typed("number", "double")
-       default:
-               return fmt.Errorf("unknown primitive %q", typeName)
        }
        return nil
 }
```

**Comment by casualjim** [comment] 2016-08-23 22:51
I wonder if this is still an issue after the merge of #633

**Comment by gaplyk** [comment] 2016-08-24 00:34
I will check tomorrow. Thank you a lot.

**Comment by casualjim** [comment] 2016-12-01 16:16
This appears to be fixed now. I'll close this one, it can always be reopened when somebody runs into it again

**Closed** 2016-12-01 16:23 UTC
Labels: bug, needs more info
