### ISSUE TITLE
make go gettable without authentication

### ISSUE THREAD

**Issue by bradrydzewski** [go-swagger/go-swagger#89] opened 2015-11-03 23:29 UTC
Hi there, we are having difficulties with `go get` recently after a submodule was added to the project. We are seeing the following errors:

```
go get -u github.com/go-swagger/go-swagger/...
# cd .; git --git-dir=/drone/src/github.com/go-swagger/go-swagger/.git submodule update --init --recursive
No submodule mapping found in .gitmodules for path 'docs/public'
```

The issue appears to be the use of a `git+ssh` url:

```
[submodule "docs/public"]
	path = docs/public
	url = git@github.com:go-swagger/go-swagger.github.io.git
```

This can be problematic for CI servers that may be building public repositories and don't have an SSH key installed on them. Without an SSH key it is unable to authenticate to GitHub and clone the repository:

```
git clone git@github.com:go-swagger/go-swagger.github.io.git
Cloning into 'go-swagger.github.io'...
The authenticity of host 'github.com (192.30.252.131)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.252.131' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Would it be possible to use `git+https` instead for the submodule?

**Comment by casualjim** [comment] 2015-11-04 01:13
I think that should be fixed now, made it reference with https 

sorry about that

**Comment by janeczku** [comment] 2015-11-05 16:22
Still not working:

```
go get -u github.com/go-swagger/go-swagger/...
# cd .; git --git-dir=/go/src/github.com/go-swagger/go-swagger/.git submodule update --init --recursive
No submodule mapping found in .gitmodules for path 'docs/public'
package github.com/go-swagger/go-swagger/...: exit status 1
```

**Comment by casualjim** [comment] 2015-11-05 19:16
I can't reproduce this :(

```shellsession
± ivan@aether:~/go/src/github.com/go-swagger/go-swagger
git:(issue-22) ✗ !? » docker pull golang
...
Status: Downloaded newer image for golang:latest

± ivan@aether:~/go/src/github.com/go-swagger/go-swagger
git:(issue-22) ✗ !? » docker run --rm -it golang go get -u github.com/go-swagger/go-swagger/... && echo "$?"
0
```

**Comment by bradrydzewski** [comment] 2015-11-06 03:21
@casualjim it has something to do with `GO15VENDOREXPERIMENT`:

```
docker run -t -i golang:1.5 /bin/bash -c "GO15VENDOREXPERIMENT=1 go get -u github.com/go-swagger/go-swagger/..."
# cd .; git --git-dir=/go/src/github.com/go-swagger/go-swagger/.git submodule update --init --recursive
No submodule mapping found in .gitmodules for path 'docs/public'
package github.com/go-swagger/go-swagger/...: exit status 1
```

with `GO15VENDOREXPERIMENT=1` it fails and with `GO15VENDOREXPERIMENT=0` it succeeds.

**Comment by casualjim** [comment] 2015-11-06 04:52
I've replaced the submodules with subtree integrations and things seem to work now.

It appears to be unhappy because the submodules have a .git file, perhaps it's this thing https://github.com/golang/go/issues/7764

**Closed by casualjim** 2015-11-06 04:52 UTC
Labels: needs more info
