### ISSUE TITLE
[Bug?] Swagger Flatten, Not Recognizing Nested Operations

### ISSUE THREAD

**Issue by nkreiger** [go-swagger/go-swagger#2908] opened 2023-03-08 16:57 UTC
## Problem statement

Swagger flatten not working as expected

## Swagger specification

```yaml
  /applications:
    get:
      $ref: 'absolute_path#/paths/~1applications/get'
    post:
      $ref: 'absolute_path#/paths/~1applications/post'
```
generates:

    /applications:
        get: {}
        post: {}

but if I move it up to the root level, works fine. I cannot do this though because I want to reference specific operations. Maybe I'm doing something wrong?

this works fine with `swagger-cli`

## Steps to reproduce

swagger flatten ... --format=yaml --with-flatten=full

## Environment
swagger version: v.30.3 
go version: 1.18.0
OS:

**Comment by fredbi** [comment] 2023-12-20 12:32
The reported problem pertains to our spec model, not just flatten.

An operation in the [swagger 2.0 specification model](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/2.0.md#operationObject) does not support externalization using $ref.

In other words, $ref is supported in well-defined places in a spec document, and cannot be used as a generic placeholder anywhere.

So this works as intended (path item object supports $ref):
```yaml
swagger: '2.0'
info:
  title: Object
  version: 0.1.0
paths:
  /applications-works:
    $ref: 'absolute_path.yaml#/paths/applications'
```
with `absolute_path.yaml`
with the following content:
 ```yaml
paths:
  applications:
    get:
      description: getter
      responses: 
        200:
          description: Ok
    post:
      description: setter
      responses: 
        200:
          description: Ok
 ```

and we flatten properly as:
```yaml
swagger: "2.0"
info:
    title: Object
    version: 0.1.0
paths:
    /applications-works:
        post:
            description: setter
            responses:
                "200":
                    description: Ok
        get:
            description: getter
            responses:
                "200":
                    description: Ok
```

but the following ignores the $ref property and the operations are empty:
```yaml
swagger: '2.0'
info:
  title: Object
  version: 0.1.0
paths:
  /applications:
    get:
      $ref: 'absolute_path.yaml#/paths/applications/get'
    post:
      $ref: 'absolute_path.yaml#/paths/applications/post'
```

**Comment by fredbi** [comment] 2023-12-20 12:35
Closing this as not a bug.

**Closed by fredbi** 2023-12-20 12:35 UTC
Labels: spec, flatten, swagger spec
