### ISSUE TITLE
Get an error "invalid character '-' in numeric literal\n\nrequest body: " when using formData.

### ISSUE THREAD

**Issue by hrsma2i** [go-swagger/go-swagger#2491] opened 2021-01-19 02:07 UTC
## Problem statement

I set a request parameter as `formData` and get the following error.

```
invalid character '-' in numeric literal\n\nrequest body: \"--------------------------2d70d43748b1608c\r\nContent-Disposition: form-data; name=\"user_id\"\r\n\r\n123\r\n--------------------------2d70d43748b1608c--\r\n\"\n
```

## Swagger specification

```yaml
swagger: "2.0"
consumes:
  - application/json
produces:
  - application/json
schemes:
  - http
paths:
  /v1/users:
    post:
      operationId: postUser
      consumes:
        - multipart/form-data
      parameters:
        - name: image
          type: file
          in: formData
        - name: user_id
          type: integer
          format: int64
          in: formData
          required: true
```

## Steps to reproduce

Execute the following commands.

```sh
# Set up the server
$ go run ./cmd/myapp-server/main.go --host 0.0.0.0 --port 8080

# Request
$ curl -X POST \
    -H "Content-Type: multipart/form-data" \
    -F user_id=123 \
    http://localhost:8080/v1/users
```

## Environment
swagger version: 0.25.0
go version: 1.15.6
OS: macOS Catalina 10.15.7

**Comment by fredbi** [comment] 2021-01-19 08:33
Hey. Just tried this on the current master (fresh v0.26.0) and it works just fine.

[tests below carried out on Linux, go1.15.3, curl 7.58.0)

1. Completed your spec a bit
```yaml
swagger: "2.0"
info:
  title: "fixture 2491"
  version: "0.0.1"
  description: "repro issue 2491"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
consumes:
  - application/json
produces:
  - application/json
schemes:
  - http
paths:
  /v1/users:
    post:
      operationId: postUser
      consumes:
        - multipart/form-data
      parameters:
        - name: image
          type: file
          in: formData
        - name: user_id
          type: integer
          format: int64
          in: formData
          required: true
      responses:
        200:
          description: ok
        default:
          description: faul
```

2. Build and run
Generating a server
```bash
swagger generate server -f fixture-2491.yaml --target gen
```
Hacking a trivial handler:
`gen/restapi/configure_fixture2491.go`:
```go
...
        api.JSONProducer = runtime.JSONProducer()

        // You may change here the memory limit for this multipart form parser. Below is the default (32 MB).
        // operations.PostUserMaxParseMemory = 32 << 20

        api.PostUserHandler = operations.PostUserHandlerFunc(func(params operations.PostUserParams) middleware.Responder {
                log.Printf("received user_id: %d", params.UserID)
                if params.Image != nil {
                        if namedFile, ok := params.Image.(*runtime.File); ok {
                                log.Printf("received file name: %s", namedFile.Header.Filename)
                                log.Printf("received file size: %d", namedFile.Header.Size)
                        }
                }
                return operations.NewPostUserOK()
        })
...
```

```bash
cd gen/cmd/*
go build
./fixture2491-server  --port 8080
2021/01/19 09:20:46 Serving fixture2491 at http://127.0.0.1:8080
```

3. Now posting a request with a user ID:
```bash
 curl -v -X POST -H "Content-Type: multipart/form-data" -F user_id=123   http://localhost:8080/v1/users
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> POST /v1/users HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.58.0
> Accept: */*
> Content-Length: 145
> Content-Type: multipart/form-data; boundary=------------------------f4c9986646eb5c58
> 
< HTTP/1.1 200 OK
< Date: Tue, 19 Jan 2021 08:25:08 GMT
< Content-Length: 0
< 
* Connection #0 to host localhost left intact
```
Checking the server logs:
```
2021/01/19 09:25:08 received user_id: 123
```

4. Now posting a request with a file:

```bash
 curl -v -X POST -H "Content-Type: multipart/form-data" -F user_id=123  -F image=@zoom.png http://localhost:8080/v1/users
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> POST /v1/users HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.58.0
> Accept: */*
> Content-Length: 93961
> Content-Type: multipart/form-data; boundary=------------------------f44e8e216d7df7f2
> Expect: 100-continue
> 
< HTTP/1.1 100 Continue
< HTTP/1.1 200 OK
< Date: Tue, 19 Jan 2021 08:27:01 GMT
< Content-Length: 0
< 
* Connection #0 to host localhost left intact
```
Checking the server logs:
```
2021/01/19 09:27:01 received user_id: 123
2021/01/19 09:27:01 received file name: zoom.png
2021/01/19 09:27:01 received file size: 93676
```

**Comment by fredbi** [comment] 2021-01-21 14:41
I've identified the root cause of this. The problem is a subtle race with various package level init() that set the spec loader.
The symptom you see is a yaml spec incorrectly loaded as json.

The work around pending the fix (probably over next week) is to convert your spec to json.

**Comment by hrsma2i** [comment] 2021-01-23 06:40
@fredbi 
Thank you for your replying.

I tried to generate codes using json spec instead of yaml spec, but I got the same error.

I also tried to use v0.26.0 and got the following error when running the server:

```
undefined: validate.WithOperationRequest
```

**Comment by fredbi** [comment] 2021-01-23 18:49
@hrsma2i  my comment above seems irrelevant.
I cannot reproduce on Linux. Could you please try reproducing your issue (I mean the first you reported) with the full test case that I have used. Please add your curl commands and share the output of `curl --version`

**Comment by fredbi** [comment] 2021-01-23 18:54
The second issue you have reported on v0.26.0 remains mysterious to me. It seems unrelated to the first one. Could you please open a separate issue and share the relevant elements (spec, an excerpt of the failing generated code). Thanks

**Comment by argarner** [comment] 2021-01-25 03:11
> The second issue you have reported on v0.26.0 remains mysterious to me. It seems unrelated to the first one. Could you please open a separate issue and share the relevant elements (spec, an excerpt of the failing generated code). Thanks

@fredbi I've just raised a new issue related to the v.0.26.0 generated code introducing this error https://github.com/go-swagger/go-swagger/issues/2498

**Comment by fredbi** [comment] 2021-02-08 09:01
@hrsma2i have you been able to reproduce this issue with v0.26.1? If so could you please add some details, like you full spec and curl command, as well as the curl output.
You can PM this info on our slack channel if you think some of this cannot be disclosed on this public github issue.

**Comment by fredbi** [comment] 2023-12-27 23:32
Stalled issue. Could never reproduce. Closing.

**Closed by fredbi** 2023-12-27 23:32 UTC
Labels: generator, cant reproduce
