### ISSUE TITLE
Not able to add response schema properties without embedded structs

### ISSUE THREAD

**Issue by tobocop** [go-swagger/go-swagger#270] opened 2016-02-09 22:07 UTC
Is there an alternative to using embedded structs to populate response schema properties?

I'm using go-swagger to generate a swagger spec from existing go-code and ran into something interesting. It looks as though the only way to get response fields to show under "responses > my-response-struct > schema > properties" is to structure the go types as embedded structs. For example:

```go
// Some response object i want to generate a swagger spec for
// swagger:response my-response
type MyResponse struct {
	SomeField      string
	SomeOtherField string
}
```

Generates:
```json
"responses": {
        "my-response": {
            "description": "A Style returns all the information for a particular style",
            "headers": {
                "SomeField": {
                    "type": "string"
                },
                "SomeOtherField": {
                    "type": "string"
                }
            }
        }
}
```

The only way to get it in the schema properties where I'd expect it is to change my struct to this:
```go
// Some response object i want to generate a swagger spec for
// swagger:response my-response2
type MyEmbeddedResponse struct {
	//in: body
	EmbeddedThing struct {
		SomeField      string
		SomeOtherField string
	}
}
```

Which then results in my expected swagger spec:
```json
 "my-response2": {
            "description": "Some response object i want to generate a swagger spec for",
            "schema": {
                "properties": {
                    "SomeField": {
                        "type": "string"
                    },
                    "SomeOtherField": {
                        "type": "string"
                    }
                },
                "type": "object"
            }
        },
```

**Comment by casualjim** [comment] 2016-02-10 01:43
the spec struct doesn't have to be embedded but it does want it to be a struct.
is that a problem for you?

**Comment by casualjim** [comment] 2016-02-15 02:21
The reason it is the way it is, is because a response to swagger is headers + body and go-swagger wants to preserve that structure.  In terms of typing effort it's about the same as an approach that uses comments only but you get verification of your types through the compiler. 

duplicate of #140

**Closed by casualjim** 2016-02-15 02:21 UTC
Labels: duplicate, invalid
