### ISSUE TITLE
Go-swagger v0.12.0 - invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by bobvanluijt** [go-swagger/go-swagger#1171] opened 2017-09-15 10:09 UTC
## Problem statement

On Mac, go-swagger v0.12.0, the command: `swagger generate server --name=weaviate --spec=https://raw.githubusercontent.com/weaviate/weaviate-swagger/develop/weaviate-swagger.json --default-scheme=https` fails with:

```
2017/09/15 12:07:07 building a plan for generation
2017/09/15 12:07:07 planning definitions
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xd pc=0x156bc09]

goroutine 1 [running]:
github.com/go-swagger/go-swagger/generator.(*schemaGenContext).makeGenSchema(0xc42079a000, 0xc421fbcf34, 0x6)
	/go/src/github.com/go-swagger/go-swagger/generator/model.go:1390 +0x5f9
github.com/go-swagger/go-swagger/generator.(*schemaGenContext).buildProperties(0xc42079b800, 0xc42079b8a8, 0x100)
	/go/src/github.com/go-swagger/go-swagger/generator/model.go:660 +0x304
github.com/go-swagger/go-swagger/generator.(*schemaGenContext).makeGenSchema(0xc42079b800, 0x0, 0xc421355740)
	/go/src/github.com/go-swagger/go-swagger/generator/model.go:1433 +0x9f3
github.com/go-swagger/go-swagger/generator.makeGenDefinitionHierarchy(0xc421fbd4b0, 0xf, 0xc421296c88, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/go-swagger/go-swagger/generator/model.go:166 +0x32c
github.com/go-swagger/go-swagger/generator.makeGenDefinition(0xc421fbd4b0, 0xf, 0xc421296c88, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/go-swagger/go-swagger/generator/model.go:133 +0xbc
github.com/go-swagger/go-swagger/generator.(*appGenerator).makeCodegenApp(0xc42064a0f0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/go-swagger/go-swagger/generator/support.go:608 +0x5d9
github.com/go-swagger/go-swagger/generator.(*appGenerator).Generate(0xc42064a0f0, 0x8, 0x0)
	/go/src/github.com/go-swagger/go-swagger/generator/support.go:260 +0x94
github.com/go-swagger/go-swagger/generator.GenerateServer(0x7fff5fbffab7, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc4203f05a0, 0xc420646270, ...)
	/go/src/github.com/go-swagger/go-swagger/generator/support.go:43 +0xcb
github.com/go-swagger/go-swagger/cmd/swagger/commands/generate.(*Server).Execute(0xc42069d600, 0xc420745450, 0x0, 0x5, 0xc42069d600, 0x1)
	/go/src/github.com/go-swagger/go-swagger/cmd/swagger/commands/generate/server.go:118 +0x54a
github.com/go-swagger/go-swagger/vendor/github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc42022dc20, 0xc42000e0d0, 0x5, 0x5, 0x100f168, 0x30, 0xc42040c870, 0xc42046f600, 0xc42046ef48)
	/go/src/github.com/go-swagger/go-swagger/vendor/github.com/jessevdk/go-flags/parser.go:316 +0x893
github.com/go-swagger/go-swagger/vendor/github.com/jessevdk/go-flags.(*Parser).Parse(0xc42022dc20, 0x6, 0x17a413a, 0x6, 0x0, 0x17ec525)
	/go/src/github.com/go-swagger/go-swagger/vendor/github.com/jessevdk/go-flags/parser.go:186 +0x73
main.main()
	/go/src/github.com/go-swagger/go-swagger/cmd/swagger/swagger.go:105 +0x858
```

Thanks in advance

**Comment by casualjim** [comment] 2017-09-15 15:59
can you include the spec that triggers this?

**Comment by bobvanluijt** [comment] 2017-09-21 15:45
Update, the swagger file was incorrectly formatted.

Funny thing, it did pass the `swagger validate` command though, to recreate the issue you can use the swagger file as mentioned above.

**Comment by Ravenwater** [comment] 2017-09-29 18:12
receiving the same error. @bobvanluijt  Can you elaborate on what incorrect formatting triggers the segfault?

**Comment by bobvanluijt** [comment] 2017-09-29 18:17
@johnciocoiu can you help @Ravenwater?

**Comment by casualjim** [comment] 2017-09-29 18:19
I can't reproduce this issue though with what's on master.

**Comment by johnciocoiu** [comment] 2017-09-30 07:57
@bobvanluijt @Ravenwater 

Somewhere in the swagger we used `type: array` for a property, without setting the 'items'. I think that was the thing causing the error in our case.

**Comment by Ravenwater** [comment] 2017-10-06 13:55
@casualjim did you receive the spec file through email to try to reproduce it?

**Comment by Ravenwater** [comment] 2017-10-06 14:54
I have narrowed it down to this data definition:

  regiment:
    type: object
    items:
      $ref: "#/definitions/demand"

  demand:
    type: object
    required:
      - package
      - plan
    properties:
      package:
        type: string
      plan:
        type: number
        format: float

Add this, and it produces the error:
$ swagger generate server -f mp-scoring-api-bad.yaml -P models.Principal
2017/10/06 10:51:07 building a plan for generation
2017/10/06 10:51:07 planning definitions
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0xd pc=0x957b6a]

goroutine 1 [running]:
github.com/go-swagger/go-swagger/generator.(*schemaGenContext).NewSliceBranch(0xc0431be000, 0xc043e91d40, 0x1)
        C:/Users/tomtz/dev/Golang/src/github.com/go-swagger/go-swagger/generator/model.go:387 +0x54a
github.com/go-swagger/go-swagger/generator.(*schemaGenContext).buildArray(0xc0431be000, 0x0, 0x0)
        C:/Users/tomtz/dev/Golang/src/github.com/go-swagger/go-swagger/generator/model.go:1068 +0x14a
github.com/go-swagger/go-swagger/generator.(*schemaGenContext).buildItems(0xc0431be000, 0x0, 0x0)
        C:/Users/tomtz/dev/Golang/src/github.com/go-swagger/go-swagger/generator/model.go:1104 +0xbfc
github.com/go-swagger/go-swagger/generator.(*schemaGenContext).makeGenSchema(0xc0431be000, 0xc0431be000, 0xc043c17d00)
        C:/Users/tomtz/dev/Golang/src/github.com/go-swagger/go-swagger/generator/model.go:1445 +0xab2
github.com/go-swagger/go-swagger/generator.makeGenDefinitionHierarchy(0xc04416e290, 0x8, 0xc0435b2830, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        C:/Users/tomtz/dev/Golang/src/github.com/go-swagger/go-swagger/generator/model.go:166 +0x2f6
github.com/go-swagger/go-swagger/generator.makeGenDefinition(0xc04416e290, 0x8, 0xc0435b2830, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        C:/Users/tomtz/dev/Golang/src/github.com/go-swagger/go-swagger/generator/model.go:133 +0xc3
github.com/go-swagger/go-swagger/generator.(*appGenerator).makeCodegenApp(0xc0432e2000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        C:/Users/tomtz/dev/Golang/src/github.com/go-swagger/go-swagger/generator/support.go:596 +0x59d
github.com/go-swagger/go-swagger/generator.(*appGenerator).Generate(0xc0432e2000, 0x0, 0x0)
        C:/Users/tomtz/dev/Golang/src/github.com/go-swagger/go-swagger/generator/support.go:254 +0xbd
github.com/go-swagger/go-swagger/generator.GenerateServer(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc042062960, 0xc042675f68, ...)
        C:/Users/tomtz/dev/Golang/src/github.com/go-swagger/go-swagger/generator/support.go:43 +0xd2
github.com/go-swagger/go-swagger/cmd/swagger/commands/generate.(*Server).Execute(0xc0427706e0, 0xc042631860, 0x0, 0x6, 0xc0427706e0, 0x1)
        C:/Users/tomtz/dev/Golang/src/github.com/go-swagger/go-swagger/cmd/swagger/commands/generate/server.go:120 +0x55e
github.com/go-swagger/go-swagger/vendor/github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc042631800, 0xc042066010, 0x6, 0x7, 0x4111ef, 0xc0422be6c0, 0xc042317400, 0xc0423d1201, 0xc042726cc0)
        C:/Users/tomtz/dev/Golang/src/github.com/go-swagger/go-swagger/vendor/github.com/jessevdk/go-flags/parser.go:316 +0x834
github.com/go-swagger/go-swagger/vendor/github.com/jessevdk/go-flags.(*Parser).Parse(0xc042631800, 0x6, 0xb9ebfb, 0x6, 0x0, 0xbe6d2e)
        C:/Users/tomtz/dev/Golang/src/github.com/go-swagger/go-swagger/vendor/github.com/jessevdk/go-flags/parser.go:186 +0x78
main.main()
        C:/Users/tomtz/dev/Golang/src/github.com/go-swagger/go-swagger/cmd/swagger/swagger.go:105 +0xd6a

next step is to drill down in the stack trace...

**Comment by casualjim** [comment] 2017-10-06 15:20
Yes sorry I've been busy with work stuff. I'll try to take a look at it
soon.

---
Met vriendelijke groeten - Best regards - Salutations
Ivan Porto Carrero - Mob: +1 (415) 323-8084
Web: http://flanders.co.nz
Twitter: http://twitter.com/casualjim

**Comment by casualjim** [comment] 2017-10-06 17:50
The issue in the spec you sent that `items` is being used with `type: object`
I'm debugging this by running the following command:

```
DEBUG=1 swagger generate server -A MpScoring -f mp-scoring-api.yaml
```

it will fail and then you'll see something like this:

```
2017/10/06 10:16:29 model.go:1051: returning after ref
2017/10/06 10:16:29 new slice branch l2_itemized_services (model: l2_itemized_services)
2017/10/06 10:16:29 cloning context l2_itemized_services
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xd pc=0x1552233]

goroutine 1 [running]:
github.com/go-swagger/go-swagger/generator.(*schemaGenContext).NewSliceBranch(0xc422064000, 0xc42227db00, 0xc420890001)
```

in this failure I see the model is l2_itemized_services

```
2017/10/06 10:16:29 new slice branch l2_itemized_services (model: l2_itemized_services)
```

after changing the type from object to array generation gets past that.

**Comment by Ravenwater** [comment] 2017-10-06 17:54
Was just typing the same observation regarding the incorrect use of type: object where there needs to be a type: array. when your update came in. 

Thank you for the DEBUG=1 trick, that will help me in the future.

Very much appreciated.

**Comment by kreamyx** [comment] 2017-10-27 18:50
Now go-openapi/validate verifies that this issue won't happen again

**Comment by sklemmer** [comment] 2017-11-08 09:32
i faced the same issue by using 
```yaml
      responses:
        '200':
          description: successful operation
          schema:
            type: object
            items:
              $ref: '#/definitions/Server'
```

which results in 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x9 pc=0x1561f56]

goroutine 1 [running]:
github.com/go-swagger/go-swagger/generator.(*schemaGenContext).NewSliceBranch(0xc420149200, 0xc4215ec480, 0xc420b50001)
        /go/src/github.com/go-swagger/go-swagger/generator/model.go:391 +0x116
```

@kreamyx so your saying that swagger validate should detect this error? when i run `swagger validate` it returns with valid spec

```
~/swagger validate api-description.yaml

The swagger spec at "api-description.yaml" is valid against swagger specification 2.0
```

**Comment by gregmarr** [comment] 2017-11-08 15:03
This panic should be fixed in `master`.

**Comment by kreamyx** [comment] 2017-11-08 18:20
@sklemmer yes `validate` detects the error if you are on master

**Closed** 2017-12-05 20:24 UTC
