### ISSUE TITLE
Unexpected generate server models when using allOf

### ISSUE THREAD

**Issue by cmhakkim** [go-swagger/go-swagger#740] opened 2016-11-15 09:38 UTC
## Problem statement

Generating go-swagger server with objects containing only allOf list produces unexpected models.

Version: dev (`go get -u github.com/go-swagger/go-swagger/cmd/swagger` today, Nov 15th, 2016).
Has been happening since I started to use go-swagger in Sep/Oct.

## Swagger specification

"Swagger allows combining and extending model definitions using the allOf property of JSON Schema, in effect offering model composition."

## Steps to reproduce

Create a $GOPATH/src/.../swagger.yaml -file with the following contents:
```yaml
swagger: "2.0"

info:
  title: allOf
  description: allOf bug example
  version: 0.0.1

schemes:
  - http

consumes:
  - application/json
produces:
  - application/json

definitions:

  Lol:
    type: object
    required:
      - xxx
      - yyy
      - zzz
    properties:
      xxx:
        type: string
      yyy:
        type: integer
      zzz:
        type: boolean

  Foo:
    type: object
    properties:
      fauna:
        $ref: "#/definitions/Lol"
      flora:
        $ref: "#/definitions/Lol"
      fungi:
        $ref: "#/definitions/Lol"

  Bar:
    type: object
    allOf:
      - $ref: "#/definitions/Foo"

  Baz:
    type: object
    properties:
      squirrel:
        type: string
      owl:
        type: string
      fox:
        type: string

  Awol:
    type: object
    allOf:
      - $ref: "#/definitions/Bar"
      - $ref: "#/definitions/Baz"

paths:

  /awol:
    put:
      operationId: setAwol
      summary: Set Awol
      parameters:
        - name: awol
          in: body
          required: true
          description: Awol
          schema:
            $ref: "#/definitions/Awol"
      responses:
        201:
          description: Awol set
          schema:
            $ref: "#/definitions/Awol"
```
$ generate server -f swagger.yaml

You'll find out that e.g. type Bar struct in models/bar.go is empty.

You can work around this by changing the definition of Bar as follows:
```
  Bar:
    type: object
    allOf:
      - $ref: "#/definitions/Foo"
      - properties:
          wut:
            type: boolean
            default: true
```

**Comment by gregmarr** [comment] 2016-11-15 16:32
In my case, I could also work around it like this:

  Bar:
    allOf:
      - $ref: "#/definitions/Foo"
      - type: object
 
@casualjim This is the thing that we talked about on Slack last week that I hadn't had time to log yet.

**Comment by casualjim** [comment] 2016-11-26 07:39
duplicate of #541, closing this one.

**Closed** 2016-11-26 19:09 UTC
Labels: bug, duplicate
