### ISSUE TITLE
Flatten stopped processing nested directories in v0.26.0

### ISSUE THREAD

**Issue by nikitakalyanov** [go-swagger/go-swagger#2743] opened 2022-03-21 09:12 UTC
## Problem statement
A certain structure of directories and files worked before v0.26.0 and stopped working after this version. It also does not work with the latest version either.

## Swagger specification
https://github.com/nikitakalyanov/go-swagger-test
## Steps to reproduce
https://github.com/nikitakalyanov/go-swagger-test

## Environment
swagger version: 0.26.0  
go version: 1.15.6  
OS:   Docker image

From the error message it seems that relative paths are now resolved differently. Could we document it somewhere then?
The workaround for now is to flatten the structure manually - i.e. remove the 'paths/' directory and put the mypath1.yml and mypath2.yml files at the root level.

**Comment by fredbi** [comment] 2023-12-22 21:13
Yes, the previous behavior was incorrect, not resolving references from the current document's.
I can't remember exactly when this was fixed.
So now, references in the "paths" folder must reference to definitions as "../definitions/....yaml#...", which is more correct.

Like so:
```yaml
get:
  produces:
    - "application/json"
  responses:
    200:
      description: "OK"
      schema:
        $ref: "../definitions/resp1.yml#/Resp1"
    500:
      description: "Internal server error"
      schema:
        $ref: "../definitions/errors.yml#/ErrorResponse"
`````

I could verify that the specs flatten properly then.

**Comment by mateusbandeiraa** [comment] 2024-01-04 14:58
There appears to be an inconsistency whether the path is resolved from the files directory instead of the root directory. This is what I mean:

Using `fixtures\bugs\2258\bar.yml` as a starting point for this example:

```yml
get:
  responses:
    200:
      description: OK
      schema:
        type: array
        items:
          $ref: '../user/index.yml#/User' ## this doesn't work
    500:
      description: OK
      schema:
        type: array
        items:
          $ref: './swagger/user/index.yml#/User' ## this works
```

(https://github.com/mateusbandeiraa/go-swagger/blob/2a8cb9362d05a9131d3278eb21f76152be1ff598/fixtures/bugs/2258/swagger/paths/bar.yml#L1-L14)

From what you said, the `$ref` should be `'../user/index.yml#/User'`. But this doesn't work. What actually works is `'./swagger/user/index.yml#/User'`.

With the `200` response, here's the error message: `could not resolve schema: open /go/user/index.yml: no such file or directory`.
Without it, it completes the flattening correctly.

**Comment by fredbi** [comment] 2024-01-04 15:52
Running flatten with current master on fixture 2258. Seems to work as expected.

```bash
cd fixtures/bugs/2258
swagger flatten --format yaml fixture-2258.yaml 
2024/01/04 16:47:21 format =  yaml
```
```yaml
swagger: "2.0"
info:
    title: Simple API
    version: 0.0.0
paths:
    /bar:
        get:
            responses:
                "200":
                    description: OK
                    schema:
                        $ref: '#/definitions/user'
    /foo:
        get:
            responses:
                "200":
                    description: OK
                "500":
                    description: OK
                    schema:
                        $ref: '#/definitions/errorPayload'
    /nested:
        get:
            responses:
                "200":
                    description: OK
                    schema:
                        $ref: '#/definitions/sameFileReference'
definitions:
    errorDetailsItem:
        description: Represents an item of the list of details of an error.
        properties:
            code:
                type: string
            details:
                items:
                    type: string
                type: array
            message:
                type: string
        required:
            - message
            - code
        title: Error details item
    errorPayload:
        properties:
            errors:
                items:
                    $ref: '#/definitions/errorDetailsItem'
                type: array
        required:
            - errors
        title: Error Payload
    model:
        properties:
            name:
                type: string
        type: object
    sameFileReference:
        properties:
            name:
                type: string
        type: object
    user:
        $ref: '#/definitions/model'
```

The bar.yml document is located in ./swagger/paths
It refers to another document in the sibling folder ../user/index.yml
So far so good.

I didn't quite understand what you tried to run and what doesn't work specifically.

**Comment by mateusbandeiraa** [comment] 2024-01-04 16:05
Just pushed a tidier couple of examples.

### Working:
![image](https://github.com/go-swagger/go-swagger/assets/15495980/210df4d9-5540-4ceb-8512-b4b61d4b8334)
https://github.com/go-swagger/go-swagger/blob/809195a882718648d9647ed12a44ab2071936ba0/fixtures/bugs/_working-example/swagger/paths/bar.yml#L1-L8
https://github.com/go-swagger/go-swagger/tree/809195a882718648d9647ed12a44ab2071936ba0/fixtures/bugs/_working-example

### Non-working:
![image](https://github.com/go-swagger/go-swagger/assets/15495980/3adf47dd-3c6d-4b78-9744-677501cc2909)
https://github.com/go-swagger/go-swagger/blob/809195a882718648d9647ed12a44ab2071936ba0/fixtures/bugs/_non-working-example/swagger/paths/bar.yml#L1-L8
https://github.com/go-swagger/go-swagger/tree/809195a882718648d9647ed12a44ab2071936ba0/fixtures/bugs/_non-working-example

**Comment by fredbi** [comment] 2024-01-08 09:42
@mateusbandeiraa thanks for the detailed example. I've been able to reproduce your issue. It looks like this is a valid bug.

**Closed** 2024-01-10 07:58 UTC
Labels: bug, Ref resolution, flatten, pending PR
