### ISSUE TITLE
Responses defined in schema: restapi/operations/xxx_responses.go:54:18: cannot make type models.YY

### ISSUE THREAD

**Issue by fredbi** [go-swagger/go-swagger#1260] opened 2017-11-10 18:27 UTC
## Problem statement
Server generation.

When response schema is specified by $ref which defines an array structure, the generated model is not correct and does not compile, with a "cannot make [type]" error.
Namely, the initialization of the structure ( {{ Schema.Zero}} initialization method) does not reflect the generated nature of the type.

- generated type with $ref uses an 'OAI' type alias and a struct:
```
type xxx struct {
   OAIxxx 
}
```
- generated OAI alias:
`type OAIxxx []string`

When no ref is used (e.g. array declared inline in the definitions of the 
swagger file), there is no "OAI" alias type and compilation proceeds normally.

When the type is an object and not an array, the generator recognize this type as a complex type and does not attempt to use the make built-in to initialize it.

The problem really here is to assimilate type X and type Y struct { X }, which the compiler does not accept.

One would expect the code generated with $ref to be identical to the one with inline schema.

## Swagger specification
2.0

## Steps to reproduce
swagger specification YAML
[test3-ter-swagger.yaml.txt](https://github.com/go-swagger/go-swagger/files/1462315/test3-ter-swagger.yaml.txt)

JSON schema referred to
[test3-ter-model-schema.json.txt](https://github.com/go-swagger/go-swagger/files/1462317/test3-ter-model-schema.json.txt)

```
swagger generate server -f ../../models/test3-ter-swagger.yaml
```

Move to cmd/{server} directory then:
```
>go build
# .../restapi/operations
../../restapi/operations/get_all_responses.go:54:18: cannot make type models.B
```
## Environment
swagger version: build from source origin/master
```
>git describe
0.12.0-49-g783e5bb
```

go version: 1.9
OS:   linux ubuntu.14.04

**Comment by fredbi** [comment] 2017-11-10 18:33
In my opinion, all these problems with $ref (#1258, #1259, #1260) are linked to a fundamental defect in the resolution of references, namely, the design choice to "flatten" things (probably for easier caching).

Ok I got it, if I flatten everything with no $ref, I 'll get it allright...
But this would defeat the purpose of SWAGGER spec '$ref' feature, that is allowing for heavy reuse of the underlying data model as message definitions for the interface.

**Comment by casualjim** [comment] 2017-11-10 19:51
there are 2 different use cases here.

1. editing specs and sharing pre-existing schemas by using references and promoting reuse
2. generating code where on an API boundary what goes over the wire has no concept of reuse or types just shapes of data.

So whether we flatten prior to the generation process or during the generation process by resolving refs ad-hoc should be of no consequence. The shape of the data is the same. The generation process works as follows:

1. resolve remote references and make them local
2. move all anonymous schemas into definitions and give them a name
3. generate an intermediate DOM (AST) from the specification that can be used for code generation
4. Pass AST to a number of templates and render code based on the information within the AST.

**Comment by fredbi** [comment] 2017-11-11 09:04
Thank you Ivan for your reply. Agree with your definitions of the use cases.
Agree too that flattening should, theoretically, makes no difference(unless we get type naming conflicts in the definition tree, which might occur, but let's put that aside...).

My opinion above was supported by my investigations of the various $ref issues found yesterday, in particular the way the modifiyRef() works. I may have misinterpreted its inner workings, as I am not (yet) familiar with the code base.
In the reported case ('xxx has no key', #1258), the generator desperately tries to find the key a the root of definitions when it has been defined deeper by the $ref. I inferred (perhaps mistakenly) that the flattening was the problem.

**Comment by casualjim** [comment] 2017-12-07 01:26
The problem is with the id field which openid 2.0 doesn't support.

**Comment by fredbi** [comment] 2017-12-07 09:38
@casualjim I have to disagree with your explanation:
- I tested with and without id or $id in the JSON schema part: same behaviour
- id or $id JSON schema keywords are not explicitly unsupported in OpenAPI 2.0, this precision comes from 3.0
[as per https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md, I could not find an equivalent to 3.0's: https://swagger.io/docs/specification/data-models/keywords)

However, it is interesting to get this view and move it to the spec validator. In this case, we should chose wether to ignore "id" or "$id" (I don't think it is used for $ref resolution anyhow) or to have the spec validate shoot a validation error on this. 

I'll work next week on the spec validation part, as I found out I spent too much time cleaning my (long) specs figuring out errors.

**Comment by casualjim** [comment] 2017-12-07 21:25
see here: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#schemaObject

the supported properties are the ones defined in that list

**Comment by fredbi** [comment] 2017-12-08 08:55
Todo on that one:
- [ ] Test the effect of #1285 on the reported test cases
- [ ] Test the impact of id and $id in this context
- [ ] Move id, $id dectection to spec validation layer, with error or warning (to be decided, depending on impact)

**Comment by kreamyx** [comment] 2017-12-08 17:27
Oh the issue is not with the $id
The problem is, the code generated has this line
`payload = make(models.B, 0, 50)` in get_all_responses.go

B is defined as
```
// B b
// swagger:model b
type B struct {
	BOAIGen
}
```

and BOAIGen is defined as
```
// BOAIGen b OAI gen
// swagger:model bOAIGen
type BOAIGen []string
```
So I am guessing the code generator is embedding the BOAIGen when it shouldn't

**Comment by fredbi** [comment] 2017-12-08 18:59
Thanks Karim. this is exactly what I observed (and hopefully, reported).
So do we all agree that Id /$Id is something that should probably be a warning in spec validate (I can take cae of that)?

The problem specifically here is that the analyzer does not recognize that "B" is a "complex type" that should not be zeroed with make().

This has something to do with the $ref (inline schema works) but should be narrowed to the array case (object works). I may try to narrow it further, as a I only tested the Response case. I didn't check the behaviour for param in this case.

**Comment by kreamyx** [comment] 2017-12-08 19:12
For $id, I will let @casualjim answer that but in general, $id is almost already supported https://github.com/go-openapi/spec/blob/master/expander.go#L629

The only case where $id is not supported is when a $ref is pointing to a subschema that doesn't have an $id but inherits its $id from a parent schema/subschema.

To support this case, any $ref should not only get resolved but the whole file pointed to by the $ref should get analyzed to identify the $id of the particular subschema the $ref is pointing to.

**Comment by fredbi** [comment] 2018-03-06 23:32
I remove the relationship to "$ref": the problem lies with the correct identification of a composed structure by the generator. I believe that forcing the Zero when composing struct should work.

**Comment by fredbi** [comment] 2018-03-10 12:13
Situation is much better with spec updated to master: thanks to the response expansion, OAIxxx types are now gone.
There is still a little glitch with the response template which omits proper pointer assignment then that should be ok. Plan to fix that soon.

**Comment by fredbi** [comment] 2018-03-13 14:03
Update on this one.

OAIGen types may come and go, it really depends on the $ref situation. This problem is related to the flatten vs expand problem and is more general.

On the other hand, I could work around the issue in the responses.gotmpl template (detecting type aliasing and being more careful about using `make` for arrays and maps). At least it builds, even though I don't like the introduction of these technical types.

This made me wonder about this generated construct (note I replaced `make(...)` by `&models.B1{}`:
is that double nil check below here for some purpose? This code which did not compile is after all dead code in many cases, isn't it? Please advise.

```golang
// WriteResponse to the client
func (o *GetAllOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		// FRED
		// .IsArray: true
		// .IsAliased: true
		// .IsMap: false
		// .IsComplexObject: true
		// .IsNullable: false
		// .IsInterface: false
		// .Zero: make(models.B1, 0, 50)
		// .IsBaseType: false
		// From above: Payload POINTER
		payload := o.Payload
		if payload == nil {
			payload = &models.B1{}
		}

		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
```

**Closed** 2019-01-04 01:54 UTC
Labels: bug, generator, model, pending PR
