### ISSUE TITLE
Generated server does not validate input

### ISSUE THREAD

**Issue by tonyxiao** [go-swagger/go-swagger#1095] opened 2017-07-14 13:29 UTC
## Problem statement

According to the docs here https://goswagger.io/use/server.html#your-own-code

> Every incoming request is described as a bunch of input parameters which have been validated prior to calling the handler. So whenever your code is executed, the input parameters are guaranteed to be valid according to what the swagger specification prescribes.

However, in practice the server generated does not actually validate input. I'm able to not specify required properties `resource_type` or `resource_id`, or even send an empty body and the code path still reaches my route handler.

## Swagger specification
```yaml
paths:
  /resource_schema:
    put:
      tags: [ResourceSchema]
      description: Find or create a `ResourceSchema` based on the resource's type and id
      parameters:
        - in: body
          name: input
          required: true
          schema:
            type: object
            properties:
              resource_type: { $ref: '#/definitions/ResourceType' }
              resource_id: { type: string }
            required: [resource_type, resource_id]
      responses:
        200:
          description: Success
          schema: { $ref: '#/definitions/ResourceSchema' }
```

## Steps to reproduce

```
swagger generate server -t servers/go
go run servers/go/cmd/schema-service-server/main.go
```

Then make a request to the server, such as
```
curl -X PUT "http://localhost:60223/v1/resource_schema" -H "accept: application/json" -H "content-type: application/json" -d "{}"
```

## Environment
swagger version: dev (latest master as of time of issue)
go version go1.8.1 darwin/amd64
OS: macOS 10.12.5 (16F73)

**Comment by cswarth** [comment] 2017-09-11 16:30
I think this is fixed in the latest release,
```
$ swagger version
version: 0.12.0
commit: 8135eb6728e43b73489e80f94426e6d387809502

$ swagger validate spec.json
The swagger spec at "spec.json" is invalid against swagger specification . see errors :
- .swagger in body is required
- .info in body is required

$ swagger generate server -t servers/go
The swagger spec at "swagger.json" is invalid against swagger specification . see errors :
- .swagger in body is required
- .info in body is required
```

**Comment by vbence** [comment] 2017-10-03 14:08
@cswarth you are talking about validating the spec, the issue is about the generated server doing validation on http request bodies.

**Comment by protheusfr** [comment] 2018-01-19 08:28
Same issue here, I've generated a go server with a spec containing for ex this kind of parameters :
```
      parameters:
      - name: UUID
        in: path
        description: "People UUID"
        required: true
        type: string
        format: uuid
```

My `restapi/operations/object_name` contain some generated type like :
```
type GetUserPreferencesParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*People UUID
	  Required: true
	  In: path
	*/
	UUID strfmt.UUID
}
```

And `strfmt.UUID` is well defined in `GitHub.com/go-openapi/strfmt/default.go` with : 

```
// UUID represents a uuid string format
//
// swagger:strfmt uuid
type UUID string
...
// IsUUID returns true is the string matches a UUID, upper case is allowed
func IsUUID(str string) bool {
	return rxUUID.MatchString(str)
}
...
UUIDPattern = `(?i)^[0-9a-f]{8}-?[0-9a-f]{4}-?[0-9a-f]{4}-?[0-9a-f]{4}-?[0-9a-f]{12}$`
...
```

But trying to call API with a god or bad UUID format produce the same result :/
Anything to do to force formats checking ?

**Comment by fredbi** [comment] 2018-01-19 08:48
There are actually several issues related here.
First mentionned a parameter in body, that is with a schema. I believe this one works now.
Second is a parameter in path, that is with a primitive type. There are several known bug there (issues #1348, #909) and I am working on a fix (PR #1372).

@protheusfr : I believe your specific issue is related to the fact that the UUID is parsed, but actually not validated. It would be nice if you could test that the proposed WIP PR #1372 actually solves your issue or if there still remain some unexplored cases.

**Comment by protheusfr** [comment] 2018-01-22 07:59
@fredbi I will do and keep you in touch, thank you for your response.

**Comment by protheusfr** [comment] 2018-01-23 09:38
Hello @fredbi from what I understand you've merged your fix in the master branch on 16th Jan.
Then I assume I can test simply by updating my go-swagger via `go get -u github.com/go-swagger/go-swagger/cmd/swagger`.

Then I've regenerated my server via `bin/swagger  generate server -A postier -f ./swagger.yml`.
This has updated some files, adding some with a strange name like `notify_new_a_d_e_l_i_mail_parameters.go` in place of `notify_new_adelimail_parameters.go` then I've deleted the old ones (in this example `notify_new_adelimail_parameters.go`).

Despite all these changes, during my tests, when I try to get a parameter with bad UUID format (in URL), no error is raised :(

**Comment by fredbi** [comment] 2018-01-23 11:05
The fix you are referring to was specific to format "mac" and only concerned code generation. This one must integrate support in the go-openapi/validate package, which has not been merged in the vendor tree of go-swagger.

The fix regarding UUID and other formats is related to using formats in non-required simple parameters (this one is the one I am supposed to have fixed in the live branch WIP).
You should be able to validate by specifying required: true or by using a schema parameter (in body). 

My fix should be available for merge next week or so.

Strange file names is related to our "inflect" library (go-openapi/swag). The generator figures out names for variables, files, etc... from your spec input. The point is to properly analyze upper cased constructs in your names, which sometimes is not easy. The rule is to keep as one word common uppercase words, such as HTTP, ID etc... and to split the rest following a Camel case rule of thumb. 
So in your case, "DELIMail" gives "d_e_l_i_mail" in "snakized" form.
The list of common "initialisms" is available in go-openapi/swag.
You may customize this by using the CLI option, e.g.  `--additional-initialism=DELI`

**Comment by protheusfr** [comment] 2018-01-23 13:12
I confirm my parameter is `required` : 
```
      parameters:
      - name: UUID
        in: path
        description: "People UUID"
        required: true
        type: string
        format: uuid
```

but despite that, the format aren't validated.

Anyway I can wait next week for merging of the new go-openapi/validate in the vendor tree.
For "strange" naming (with is not an issue) what is strange is just that the names has changed after go-swagger upgrade and without any change in the spec.

Many thanks for your time.

**Comment by fredbi** [comment] 2018-01-23 13:49
Changes in naming have been introduced by PR#1357.
Actually, this didn't work in early december, then I added a quick patch for the release.
PR#1357 provided a better solution, letting you configure your reserved words ("initialisms").

Regarding your validation issue, the dependency on the patch on validate does not concern UUID, just MAC. Again, you may try the WIP branch from #1372 and see if it fix your issue. As I am currently testing it, I am interested in all kind of feedback (e.g. it looks like the "in": "path" causes the issue - have you tried "in": "query".

Anyhow, the plan with #1372 is to provide a more comprehensive support for simple params, including arrays, nested arrarys and default values for which there are many issus currently.

**Comment by protheusfr** [comment] 2018-01-23 15:52
`Anyhow, the plan with #1372 is to provide a more comprehensive support for simple params, including arrays, nested arrarys and default values for which there are many issus currently.`

From `master` or `fredbi:909-fix-validate-format-for-simple-param` ?

**Comment by fredbi** [comment] 2018-01-23 16:05
As soon as I've tested enough this branch and passed @casualjim review, it should be merged to master. 
I did not push a PR just to hang around forever 😺

**Comment by fredbi** [comment] 2018-02-09 10:59
Hello @protheusfr. A bunch of fixes have been merged into master today. That should improve things for simple params. We shall soon update vendor with the validation and spec package to clean up the bug scene further.

There are still some known validation shortcoming with model objects (e.g. parameters in body).

**Comment by fredbi** [comment] 2018-03-02 11:52
The remaining of this issue now corresponds to #1392 (validation of body params)

**Closed** 2018-03-09 19:20 UTC
Labels: bug, duplicate, generator, validator
