### ISSUE TITLE
Marking dictionary objects as required is ignored in generated code

### ISSUE THREAD

**Issue by Marclev78** [go-swagger/go-swagger#2415] opened 2020-10-23 12:01 UTC
## Problem statement

If a property is defined as a pure map (without any other fixed fields), making it "required" does not work in generated code.

## Swagger specification

Consider this object:

```
"properties": {
    "currencies": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#/definitions/amount"
      }
    },
},
"required": ["currency"]
```

This produces (correctly) a go representation of `map[string]Currency`. It seems however that the `required` directive is ignored, requests that do not include `currencies` are accepted and defaulted to an empty map.

I want them to be rejected as per the json-spec.

**Comment by casualjim** [comment] 2020-10-23 15:58
You have set the property `minProperties` to 1 or more. The required just checks if something is null or not

**Comment by fredbi** [comment] 2020-11-14 10:15
I'd say this is a duplicate of #2300

**Closed** 2020-11-15 20:22 UTC
Labels: additionalProperties, bug, duplicate, model, pending PR
