### ISSUE TITLE
BodyParam of type array doesn't properly generate client code

### ISSUE THREAD

**Issue by briansan** [go-swagger/go-swagger#1280] opened 2017-11-21 17:41 UTC
## Problem statement
The client parameter generated method `WriteToRequest` (found here)[https://github.com/go-swagger/go-swagger/blob/master/generator/templates/client/parameter.gotmpl#L239] seems to incorrectly omit the `SetBodyParam` when a parameter is defined as `in: body` and `schema.type: array`.

## Swagger specification
```
{
  "swagger": "2.0",
  "info": {
    "title": "GoSwaggerClientBodyParameterBug",
    "version": "2.0"
  },
  "paths": {
    "/foo": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "arrayBody",
            "in": "body",
            "description": "an array of json objects",
            "required": true,
            "schema": {
              "type": "array",
              "items": {
                "properties": {
                  "bar": {
                    "type": "string"
                  }
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad Request"
          }
        }
      }
    }
  }
}
```
## Steps to reproduce
1. use the swagger spec described above to generate the client code
2. note how the `client/operations/post_foo_parameters.go:PostFooParams.WriteToRequest` is missing the call to `r.SetBodyParam(o.ArrayBody)`

## Environment
swagger version: dev
go version: 1.9.2
OS: macOS 10.13.1

**Comment by fredbi** [comment] 2017-12-06 09:51
Is this a duplicate of #1309 (fixed by #1310)?
Would need to check if the fix apply in your case as well.

**Comment by isinelnikov** [comment] 2017-12-06 13:12
It definitely does not work with current master if body schema is type 'string' and format 'byte'. Generated client code is missing r.SetBodyParam(...).

Didn't check op's case with array.

**Comment by gregmarr** [comment] 2017-12-06 13:41
Did you try with `develop`? That's where current development is happening.

**Comment by isinelnikov** [comment] 2017-12-06 13:47
I see no 'develop' branch, only 'master' where current development is indeed happening. I checked master with #1310 pull request.

**Comment by gregmarr** [comment] 2017-12-06 14:03
Sorry, wrong project. @isinelnikov

**Comment by geret13** [comment] 2017-12-11 22:47
I am able to reproduce this issue with the current master, in my test I used an array of objects.

**Closed** 2017-12-11 23:31 UTC
Labels: bug, duplicate, need testing
