### ISSUE TITLE
Validation for extended string format

### ISSUE THREAD

**Issue by RomanBuzuk** [go-swagger/go-swagger#961] opened 2017-03-17 09:42 UTC
## Problem statement

We can define that some property has extended string format ( for example ipv4). Then go-swagger generate this property with special type ( for ipv4 it is *strfmt.IPv4). But generated code don`t do validation for this type.
## Example:
swagger.yaml 
```
definitions:
  ethernet:
    type: object
    required:
      - ip
    properties:
      id:
        type: integer
        format: int32
        readOnly: true
      ip:
        type: string
        format: ipv4
```
We get file ethernet.go with code 
```
...
type Ethernet struct {
	// id
	// Read Only: true
	ID int32 `json:"id,omitempty"`

	// ip
	// Required: true
	IP *strfmt.IPv4 `json:"ip"`
}
...
func (m *Ethernet) validateIP(formats strfmt.Registry) error {

	if err := validate.Required("ip", "body", m.IP); err != nil {
		return err
	}
	return nil
}
```
But why  it is not generated like this : 
```
func (m *Ethernet) validateIP(formats strfmt.Registry) error {

	if err := validate.Required("ip", "body", m.IP); err != nil {
		return err
	}
// check that we get string in right format
	if err := validate.FormatOf("ip", "body", "ipv4", m.IP.String(), formats); err != nil {
		return err
	}
	return nil
}
```

## Environment
swagger version: 0.8.0

**Comment by benpye** [comment] 2017-08-03 22:51
Did you ever work out what was going wrong here?

**Comment by casualjim** [comment] 2017-08-04 00:48
haven't been able to look at it for cause of the issue. I assume it's missing an opportunity to include the format validator

**Comment by fredbi** [comment] 2018-01-09 17:22
Duplicate of #909

**Closed** 2018-02-09 08:19 UTC
Labels: bug, duplicate, generator, in progress
