### ISSUE TITLE
POST client request gets a 415 response

### ISSUE THREAD

**Issue by siadat** [go-swagger/go-swagger#893] opened 2017-01-23 17:44 UTC
## Problem statement

When I send a POST request using the client API, I get a 415 (Unsupported Media Type) response. I noticed that the request has an extra header that sets "Transfer-Encoding: chunked". On the other hand, sending the POST request via curl works fine because it doesn't have that header.

This is my first go-swagger client and server. So, it is likely that I am doing something wrong, either in the code or in the swagger specification file.

Here is the request and response:
```
POST /api/v1/keys/k?value=v HTTP/1.1
Host: localhost:8001
User-Agent: Go-http-client/1.1
Transfer-Encoding: chunked
Accept: application/json
Accept-Encoding: gzip

0


HTTP/1.1 415 Unsupported Media Type
Connection: close
Content-Length: 113
Content-Type: application/json
Date: Mon, 23 Jan 2017 17:39:22 GMT

{"code":415,"message":"unsupported media type \"application/octet-stream\", only [application/json] are allowed"}
Error: unknown error (status 415): {resp:0xc4202ac120} 

```

And here is the error client is receiving:

    &runtime.APIError{OperationName:"unknown error", Response:client.response{resp:(*http.Response)(0xc420090870)}, Code:415}

## Swagger specification

```yaml
swagger: '2.0'
info:
  version: "0.0.0"
  title: Testman
schemes:
  - http
host: localhost
basePath: /api/v1
produces:
  - application/json
consumes:
  - application/json
paths:
  /keys/{key}:
    get:
      parameters:
        - name: key
          in: path
          required: true
          type: string
      responses:
        200:
          description: Successful response
        404:
          description: Not found
    post:
      parameters:
        - name: key
          in: path
          required: true
          type: string
        - name: value
          in: query
          required: true
          type: string
      responses:
        200:
          description: Successful response

```

## Steps to reproduce

I pushed everything needed to reproduce this issue at https://github.com/siadat/swagger-eg

## Environment
Swagger version: 2.0
Go version: go version devel +6a3c6c0 Sat Jan 14 05:57:07 2017 +0000 linux/amd64
OS: linux

**Comment by casualjim** [comment] 2017-01-23 19:50
The content type of your request needs to be set to application/json
At the moment it's not present and then the default is application/octet-stream

**Comment by GlenDC** [comment] 2017-01-23 21:31
I tried to reproduce your issue as follows:

```bash
go get -d github.com/siadat/swagger-eg
cd $GOPATH/src/github.com/siadat/swagger-eg
swagger generate server swagger.yaml --target=swagger
swagger generate client swagger.yaml --target=swagger
go run server.go
go run client.go
```

And it seems to work as you would think, as I get a 200OK result:

```
POST /api/v1/keys/k?value=v HTTP/1.1
Host: localhost:8001
User-Agent: Go-http-client/1.1
Content-Length: 0
Accept: application/json
Accept-Encoding: gzip


HTTP/1.1 200 OK
Connection: close
Content-Length: 0
Content-Type: application/json
Date: Mon, 23 Jan 2017 21:26:27 GMT
```

Are you sure these are the reproduction steps that you followed @siadat? Or am I missing a step? Also can you please specify the swagger version by running `swagger version`. I am assuming you running the latest (dev) version because of your Makefile. Also are you sure you're testing your server using `go run client.go` and not via `curl`/`httpie`/`postman` or w/e.

**Comment by siadat** [comment] 2017-01-24 13:09
@casualjim How do I set the content-type? I am using the generated API and I cannot find the API to change the content type or any other request header.

@GlenDC I reproduced the issue using another computer. I got the same result (415).

```
$ go version
go version devel +5b708a6 Mon Jan 16 05:40:45 2017 +0000 linux/amd64

$ swagger version
dev
```

In case it could be useful, here is the list of the last commit I have for go-swagger repo and each go-openapi repo:

```
b48220d 2017-01-23 github.com/go-swagger/go-swagger

d5a75b7 2016-12-30 github.com/go-openapi/analysis
fc3f73a 2017-01-04 github.com/go-openapi/errors
779f453 2017-01-02 github.com/go-openapi/jsonpointer
36d33bf 2016-11-05 github.com/go-openapi/jsonreference
6bb6486 2017-01-17 github.com/go-openapi/loads
3b13ebb 2017-01-19 github.com/go-openapi/runtime
593aa4c 2017-01-16 github.com/go-openapi/spec
0cb3db4 2017-01-12 github.com/go-openapi/strfmt
96d7b9e 2016-12-25 github.com/go-openapi/swag
035dcd7 2017-01-17 github.com/go-openapi/validate
```

**Comment by siadat** [comment] 2017-01-24 13:16
It might be a good idea to check the generated files, perhaps compare them with the files that were generated in your case. For this purpose, I added them to the same https://github.com/siadat/swagger-eg repo.

**Comment by siadat** [comment] 2017-01-24 13:47
Another observation; instead of

    go run server.go

I ran

    go run swagger/cmd/testman-server/main.go --port 8001

Same 415 response.

**Comment by siadat** [comment] 2017-01-24 14:37
Found it.

The client API does not work with the latest development version of Go. This is the commit on which the client API stopped working: golang/go@4859f6a

**Comment by GlenDC** [comment] 2017-01-24 14:41
I think we all use Go as in released versions. Which for me at the moment is `go version go1.7.1 darwin/amd64`

**Comment by siadat** [comment] 2017-01-24 15:21
Does that mean you are not planning to support Go 1.8? It will be out in about a week.

**Comment by GlenDC** [comment] 2017-01-24 15:26
I think it will be supported. But only when it is released. @casualjim might know more about this though.

**Comment by casualjim** [comment] 2017-01-24 15:29
we'll support it, the policy I follow is current and current - 1. So both 1.8 and 1.7 should be supported after 1.8 is released.

**Comment by siadat** [comment] 2017-01-24 15:42
Thank you.

**Comment by casualjim** [comment] 2017-01-24 15:48
Thanks for finding this, I'll look into what needs to happen to work with go 1.8 over the weekend unless somebody gets to it earlier

**Comment by aanm** [comment] 2017-03-14 04:14
What's the current status of this? I'm getting this bug with go 1.8 stable.

**Comment by mikeb333** [comment] 2017-04-21 20:07
We are encountering this error as well. Any update on this?

**Comment by casualjim** [comment] 2017-04-22 14:59
it's fixed in the runtime, just update your vendor or the package in your gopath

**Closed** 2017-04-22 14:58 UTC
Labels: bug, generator
