### ISSUE TITLE
use $ref under path cause one route not found error

### ISSUE THREAD

**Issue by merryzhou** [go-swagger/go-swagger#2137] opened 2019-12-18 07:48 UTC
## Problem statement
curl http://127.0.0.1:65475/v1/test
{"code":404,"message":"path /v1/test was not found"}

## Swagger specification
```
swagger: "2.0"
info:
  description: Test
  title: Test
  version: "0.0.1"
basePath: /v1
consumes:
  - application/json
produces:
  - application/json

paths:
  /test/a:
    $ref: "#/paths/~1test"
  /test:
    get:
      operationId: test
      responses:
        200:
          description: OK
```
## Steps to reproduce
1 . swagger generate code
2. curl http://127.0.0.1:65475/v1/test/a, response  ok
3. curl http://127.0.0.1:65475/v1/test, got a 404 error

## Environment
swagger version: v0.21.0
go version: go1.13.1
OS:   darwin/amd64

**Comment by fredbi** [comment] 2019-12-19 13:56
I believe this is a duplicate of #2113. I've been working on a fix lately. Hang on! It is coming up.
Thanks for reporting.

**Comment by fredbi** [comment] 2019-12-24 09:55
@merryzhou I've tested your case more thoroughly and here is my take:
i) if you remove the `operationId`  from the spec, everything goes smooth
ii) specifying `operationId`   makes it a duplicate entry across the board of operations, which is why it fails. The expanded spec is invalid.
iii) there is indeed a bug, but it is a spec validation bug: generation should have detected the duplicate operationId and failed before generation.

**Closed** 2020-11-28 10:17 UTC
Labels: Ref resolution, bug, duplicate, pending PR, validate spec
