### ISSUE TITLE
JSON 'unknown field' error when using allOf composition

### ISSUE THREAD

**Issue by mdelvecchio-wasabi** [go-swagger/go-swagger#2350] opened 2020-07-11 03:55 UTC
## Problem statement

I have three objects defined in my swagger:

1) A shared list of counter properties
2) An object used to store an instance of those counters (with an additional property as an index)
3) An object used to aggregate multiple instances of those counters (with an additional Count property)

The Go structs generated for 1) and 3) are as expected:

```
// SharedCounters
//
// swagger:model SharedCounters
type SharedCountersstruct {

	// Counter1
	Counter1 int32 `json:"Counter1 ,omitempty"`

	// Counter2
	Counter2 int32 `json:"Counter2,omitempty"`
}

// AggregationObject 
//
// swagger:model AggregationObject 
type AggregationObject struct {
	SharedCounters

	// Count 
	Count int32 `json:"Count,omitempty"`
}

```

One of my API operations returns this AggregationObject in its response body.  Here is an example response:

```
HTTP/1.1 200 OK
Content-Length: 111
Content-Type: application/json
Date: Sat, 11 Jul 2020 03:38:49 GMT

{"Counter1":10,"Counter2":865230,"Count":105}

```

When the client receives this object, it gets an error:

```
Error:  json: unknown field "Count"
```

This error of course does not happen when I explicitly specify the Counter1 and Counter2 properties in the AggregationObject definition.  I believe it is caused by the JSON deserialization.

Should this pattern work?

Thanks.

Please remove the sections that don't apply

## Swagger specification

```
definitions:

  SharedCounters:
    type: object

    properties:

      Counter1:
        type: integer
        x-nullable: false

      Counter2::
        type: integer
        x-nullable: false

  AggregationObject:
    type: object

    properties:

      Count:
        type: integer
        x-nullable: false

    allOf:
      - $ref: '#/definitions/SharedCounters'

```

## Environment
swagger version: v0.23.0 
go version: go1.11.5 
OS:   Ubuntu 18

**Comment by fredbi** [comment] 2020-07-11 05:26
It expects an input like this;
```
{{"Counter1":10,"Counter2":865230},"Count":105}
``

**Comment by mdelvecchio-wasabi** [comment] 2020-07-11 14:22
I think that would be the case if the Go struct were generated like this:

```
type AggregatedStruct {
   SharedCounters SharedCountersStruct
   Count int32
}
```

And further, the serializer on the server side is not producing the structure you describe; it is producing the flat structure, as that is what Go produces.  The struct has three properties, all int32:  Counter1, Counter2, and Count.

I will try to reproduce this with just the JSON seralization/deserialization later today.

Thanks.

**Comment by mdelvecchio-wasabi** [comment] 2020-07-11 17:03
So I guess this issue should be titled **swag.ReadJSON() cannot deserialize JSON for a composed object that was serialized by swg.WriteJSON()**

Here are the Swagger definitions I am using for this example:

```
  SharedCounters:
    type: object

    properties:

      Counter1:
        type: integer
        x-nullable: false

      Counter2::
        type: integer
        x-nullable: false

  AggregationObject:
    type: object

    properties:

      Count:
        type: integer
        x-nullable: false

    allOf:
      - $ref: '#/definitions/SharedCounters'
```

And here is a simple test program that I wrote that demonstrates the problem.  First, I create an instance of the AggregationObject struct:

```
	aggregationObject := &models.AggregationObject {
		SharedCounters:		models.SharedCounters{
			Counter1:	123,
			Counter2:   456,
		},
		Count: 999,
	}
	fmt.Printf ("With fmt.Printf():\n%v\n\n", *aggregationObject)
```

Then I serialize it to JSON:

```
	bytes, _ := swag.WriteJSON(aggregationObject)
	fmt.Printf ("Serialized to JSON:\n%s\n", string (bytes))
```

Then I create a second object, and attempt to deserialize the JSON just produced into that object:

```
	aggregationObject2 := models.AggregationObject{}
	err = swag.ReadJSON (bytes, &aggregationObject2)
	if err == nil {
		fmt.Printf ("Deserialized:\n%v\n", aggregationObject2)
	} else {
		fmt.Printf ("Error deserializing:  %v\n", err.Error())
	}
```

The output of the above:

```
With fmt.Printf():
{{123 456} 999}

Serialized to JSON:
{"Counter1":123,"Counter2:":456,"Count":999}

Error deserializing:  json: unknown field "Count"
```

I would expect swag.ReadJSON() to be able to parse what swag.WriteJSON() produced.  Is this assumption incorrect?

Thanks.

**Comment by casualjim** [comment] 2020-07-11 17:05
interesting, does that also fail with the default golang `json.Marshal/Unmarshal` methods?

**Comment by mdelvecchio-wasabi** [comment] 2020-07-11 17:15
I was just testing that.  This is the source I hacked:

```
// ReadJSON reads json data, prefers finding an appropriate interface to short-circuit the unmarshaler
// so it takes the fastest option available
func ReadJSON(data []byte, value interface{}) error {
	trimmedData := bytes.Trim(data, "\x00")
	if d, ok := value.(ejUnmarshaler); ok {
		jl := &jlexer.Lexer{Data: trimmedData}
		d.UnmarshalEasyJSON(jl)
		return jl.Error()
	}
	if d, ok := value.(json.Unmarshaler); ok {
		return d.UnmarshalJSON(trimmedData)
	}
	return json.Unmarshal(trimmedData, value)
}
```

There are three unmarshalers in there.  The first, d.UnmarshalEasyJSON(), is not being called.  The second, d.UnmarshalJSON(), was being called and produced this error.

I hacked it so that it instead called json.Unmarshal(), and that produced the same error.

My printouts revealed that the error comes when swag.ReadJSON() is parsing the SharedCounters object, and encounters the unknown Count field.

**Comment by casualjim** [comment] 2020-07-11 17:21
interesting that would mean we can reproduce it without any json libs involved because that would be a straight method call to the custom serializer

**Comment by mdelvecchio-wasabi** [comment] 2020-07-11 17:24
And json.Marshal() produces the same serialization as swag.WriteJSON():

```
Serialized with json.Marshal():
{"Counter1":123,"Counter2:":456,"Count":999}
```

**Comment by casualjim** [comment] 2020-07-11 17:29
For me this works though:

```yaml
consumes:
- application/json
info:
  title: Swagtest
  version: 0.1.0
paths:
  /the-thing:
    get:
      responses:
        default:
          description: all responses
          schema:
            $ref: "#/definitions/AggregationObject"
produces:
- application/json
schemes:
- http
swagger: "2.0"
definitions:

  SharedCounters:
    type: object

    properties:

      Counter1:
        type: integer
        x-nullable: false

      Counter2::
        type: integer
        x-nullable: false

  AggregationObject:
    type: object

    properties:

      Count:
        type: integer
        x-nullable: false

    allOf:
      - $ref: '#/definitions/SharedCounters'
```

```shellsession
mkdir -p /tmp/swagtest && cd $_
go mod init local/swagtest
echo $SPEC_CONTENT > swagger.yml
swagger generate client
```

```go
func main() {
	jsons := `{"Counter1":123,"Counter2:":456,"Count":999}`
	var obj models.AggregationObject
	if err := obj.UnmarshalJSON([]byte(jsons)); err != nil {
		log.Fatalln(err)
	}
	fmt.Printf("%#v", obj)
}
```

```shellsession
$ go run .
models.AggregationObject{SharedCounters:models.SharedCounters{Counter1:123, Counter2:456}, Count:999}
```

**Comment by mdelvecchio-wasabi** [comment] 2020-07-11 18:10
It does not work for me.  The call to `swag.ReadJSON(rtjson, &obj1)` returns the familiar error.

Maybe this is because my company is stuck on Go version 1.11.5.  Let me try this in the playground to see what happens...

**Comment by mdelvecchio-wasabi** [comment] 2020-07-11 18:23
Well, the parts that I can run in the Playground work there (https://play.golang.org/p/onWCcniBdXE) with Go 1.14.4:

```
	rtjson, err := swag.WriteJSON(AggregationObject{Count: 290, SharedCounters: SharedCounters{Counter1: 304, Counter2: 948}})
	if err != nil {
		log.Fatalln(err)
	}
	var obj1 AggregationObject
	if err := swag.ReadJSON(rtjson, &obj1); err != nil {
		log.Fatalln(err)
	}
	fmt.Printf("%#v\n", obj1)


	jsons := `{"Counter1":123,"Counter2:":456,"Count":999}`
	var obj AggregationObject
	if err := swag.ReadJSON([]byte(jsons), &obj); err != nil {
		log.Fatalln(err)
	}
	fmt.Printf("%#v\n", obj)
```

The output:

```
main.AggregationObject{SharedCounters:main.SharedCounters{Counter1:304, Counter2:948}, Count:290}
main.AggregationObject{SharedCounters:main.SharedCounters{Counter1:123, Counter2:456}, Count:999}
```

That code definitely fails with my older GO version.

**Comment by fredbi** [comment] 2020-07-25 05:47
@mdelvecchio-wasabi I've been testing the above playground with go1.11.5 and it works.
I cannot reproduce your issue.

You can see this here:
- draft PR adding the above as a unit test: https://github.com/go-openapi/swag/pull/49
- Travis CI  build using go1.11.5: https://travis-ci.org/github/go-openapi/swag/jobs/711670814

This code has barely changed since the advent of go1.7

**Comment by fredbi** [comment] 2020-11-17 07:31
@mdelvecchio-wasabi

I have added more thorough testing on this use case specifically to go-openapi/strfmt, including (temporarily) on go1.11.x and go1.11.5. Still not able to reproduce the reported issue. 

See: https://github.com/go-openapi/strfmt/pull/73

Closing this as this most likely relates to a go build environment issue. Feel free to reopen if you still face this issue. I'd be happy to help.

**Closed by fredbi** 2020-11-17 07:31 UTC
Labels: allOf, needs testing
