### ISSUE TITLE
embedded spec discards information from original spec

### ISSUE THREAD

**Issue by databus23** [go-swagger/go-swagger#1281] opened 2017-11-27 18:46 UTC
## Problem statement
Given this spec
```
swagger: '2.0'
consumes:
  - application/json
produces:
  - application/json
info:
  title: Test
  version: 1.0.0
securityDefinitions:
  keystone:
    type: apiKey
    in: header
    name: x-auth-token
security:
  - keystone: []
paths:
  /info:
    get:
      security: []
      responses:
        '200':
          description: OK
          schema:
            type: string

```

The embedded spec in the generated server is missing the `security: []` entry in the operation.
This is semantically different from the original spec where the global `security` setting is explicitly overridden to be empty (no authentication for this operation required).

The problem is caused by an `omitempty` [struct tag](https://github.com/go-openapi/spec/blob/a4fa9574c7aa73b2fc54e251eb9524d0482bb592/operation.go#L34). I'll open a PR there to fix this issue.

## Steps to reproduce
`swagger generate server --name test --target test swagger.yaml`

## Environment
swagger version: 0.13.0  
go version: 1.9.2
OS: Darwin

**Comment by gregmarr** [comment] 2017-11-27 19:04
@databus23 Is there a possibility that this will cause the `security: []` to appear on specs that don't currently have anything there, changing their semantics?

**Comment by databus23** [comment] 2017-11-27 19:05
no, what will appear there is `security: null` which is semantically the same as before.

**Comment by gaplyk** [comment] 2017-11-27 21:43
this changes cause an error in validator.

**Comment by gaplyk** [comment] 2017-11-27 22:36
@databus23  please reconsider your approach to fix server generator instead of fixing spec.
I can't fix spec generator to generate json files without "security": null

**Comment by gregmarr** [comment] 2017-11-27 22:46
@gaplyk That's expected according to @databus23 's post that it's semantically the same as before.  Can you provide information on why that's an error for you?

**Comment by databus23** [comment] 2017-11-27 22:47
@gaplyk Can you elaborate a bit on what the problem is? what is the problem with `security: null` in the spec generator?
I'm not sure what other ways are they to fix this. Leaving the `omiteempty` tag annotation in go-openapi/spec does not seem right to me as it causes loss of information when serialising a `spec.SwaggerSpec` struct to JSON.

**Comment by casualjim** [comment] 2017-11-27 22:52
if semantically the same how is omitempty an issue? can it be fixed with a custom marshal/unmarshal?

**Comment by gregmarr** [comment] 2017-11-27 22:55
He's saying that `security: null` is semantically the same as `omitempty`, but different than `security: []`.

**Comment by databus23** [comment] 2017-11-27 22:57
The problem with `omitempty` is that it not only removes `nil` values from the resulting JSON but empty slices `[]` as well. When you load the serialised JSON again you have no way of knowing if the original spec contained `[]` for `security` or the field was not set/nil.

**Comment by casualjim** [comment] 2017-11-27 23:07
not from a go perspective. both are empty. in go nil and [] are the same, https://play.golang.org/p/UNZ5kT2JSC

we have the same issue with validations where we have a hard time distinguishing between key not present and value not present, or value set to empty.

Would the right solution be to use a pointer? that way you can distinguish between the things more easily.

**Comment by databus23** [comment] 2017-11-27 23:12
@casualjim I can't agree .`nil` and `[]` are not the same in go. The first one is an initialised slice and the the other a slice of length 0. If you remove the `omitempty` annotation in your example you see the difference. So `omitempty` makes them look equal but they are not and they happen to mean different things for this specific field.

**Comment by gregmarr** [comment] 2017-11-27 23:14
They can indeed be distinguished without the `omitempty` 
https://play.golang.org/p/kuk2mk-dgV

**Comment by gaplyk** [comment] 2017-11-28 03:38
so do we need to rewrite json.Marshal then?

**Comment by gaplyk** [comment] 2017-11-28 03:41
the problem is when you generate spec from the code and you don't have `security` on the endpoint level you are getting `"security": null`.
this is a problem of json.Marshal then or we have to create custom Marshaller for this type.

**Comment by databus23** [comment] 2017-11-28 23:52
I played a bit with a custom marshalling function to achieve the following to points:

* keep empty array in the resulting JSON
* omit the key when the slice is unset/nil

This is what I came up with:
```
func (op OperationProps) MarshalJSON() ([]byte, error) {
	type Alias OperationProps
	if op.Security == nil {
		return json.Marshal(&struct {
			Security []map[string][]string `json:"security,omitempty"`
			*Alias
		}{
			Security: op.Security,
			Alias:    (*Alias)(&op),
		})
	}
	return json.Marshal(&struct {
		Security []map[string][]string `json:"security"`
		*Alias
	}{
		Security: op.Security,
		Alias:    (*Alias)(&op),
	})
}
```

It a little convoluted and I'm up for suggestions how to fix this more elegantly.

**Comment by genexp** [comment] 2017-11-29 13:03
Heh, yep. Bit me too :)  I hacked this in for each of my paths/methods.

```go
Security = []map[string][]string{
  map[string][]string{
   "myAPIKey": emptyslice,
  },
}
```

**Comment by databus23** [comment] 2017-11-29 14:11
I submitted https://github.com/go-openapi/spec/pull/40 to address the discussed regression

**Comment by casualjim** [comment] 2017-11-29 16:28
I merged this PR now

**Comment by fredbi** [comment] 2018-04-18 15:43
@databus23 after some tests with similar cases, it looks that #1478 solved the issue.
Can you please confirm?

**Closed** 2018-05-13 16:54 UTC
Labels: auth, bug, needs testing

**Comment by powerman** [comment] 2019-04-14 12:38
Probably this should be reopened - embedded /swagger.json returned by 0.19.0 still returns `"security":null` while in yml it's `security: []`.

**Comment by fredbi** [comment] 2019-04-14 15:50
Mmmh could it be [this](https://github.com/go-openapi/loads/commit/0d17535daa37578ec3b60494288bd3164cb9a36b) that introduced a regression? I fixed several such mishaps after this commit, but might have overlooked a few ones.

**Comment by powerman** [comment] 2019-04-14 15:52
Sounds like it's right time to add a small test for this regression. :smile:

**Comment by fredbi** [comment] 2019-04-14 16:42
@powerman there is a test [here](https://github.com/go-openapi/spec/blob/53d776530bf78a11b03a7b52dd8a083086b045e5/operation_test.go#L306) I made when fixing the regressions brought by the above-mentioned "optimization" commit. Could you help here by pointing out which use-case this test is missing?

**Comment by powerman** [comment] 2019-04-14 19:03
@fredbi At a glance it doesn't looks like these tests are relevant to the issue - problem isn't in gob/json conversion. I've just tested json output from `swagger expand`, `swagger flatten`, `swagger serve --no-ui` - all return valid json `…, "security": [ { "api_key": [] } ] …`. But my application returns invalid JSON: `…, "security": [ { "api_key": null } ] …`. You can check whole app at https://github.com/powerman/go-service-goswagger-clean-example but all it does is a very standard thing: https://github.com/powerman/go-service-goswagger-clean-example/blob/master/internal/api/api.go#L34-L39.

**Comment by powerman** [comment] 2019-04-14 19:35
Actually we can just look at generated [embedded_spec.go](https://github.com/powerman/go-service-goswagger-clean-example/blob/master/internal/api/restapi/embedded_spec.go) - as you can see, `SwaggerJSON` [contains invalid JSON](https://github.com/powerman/go-service-goswagger-clean-example/blob/master/internal/api/restapi/embedded_spec.go#L129) while `FlatSwaggerJSON` [contains valid JSON](https://github.com/powerman/go-service-goswagger-clean-example/blob/master/internal/api/restapi/embedded_spec.go#L248).

**Comment by fredbi** [comment] 2019-04-14 20:43
@powerman yes it is the gob decoder in go-openapi/loads package. This embedded spec is the only place where we call this (called from [here](https://github.com/go-swagger/go-swagger/blob/312366608bbf17dd219190b66ab63bdc8b4d0db0/generator/support.go#L519)).  Looking at your spec, I have been able to locate the culprit https://github.com/go-openapi/spec/blob/53d776530bf78a11b03a7b52dd8a083086b045e5/operation.go#L351.

In this place, one should again test for null vs empty list.

**Comment by fredbi** [comment] 2019-04-16 12:20
@powerman https://github.com/go-openapi/spec/pull/90

The problem was not exactly where I pointed out, but next to that...

Need to add a more global test in go-openapi/loads. Waiting for this PR to be merged before doing this (update dependencies etc.)
