### ISSUE TITLE
Error while generating server from spec with refs to local files

### ISSUE THREAD

**Issue by jbub** [go-swagger/go-swagger#711] opened 2016-10-21 10:05 UTC
## Problem statement

When generating simple spec it fails with:

```
swagger generate server -A Item -f ./swagger.yaml

2016/10/21 11:58:17 building a plan for generation
2016/10/21 11:58:17 planning definitions
2016/10/21 11:58:17 planning operations
2016/10/21 11:58:17 grouping operations into packages
2016/10/21 11:58:17 planning meta data and facades
2016/10/21 11:58:17 rendering 0 models
2016/10/21 11:58:17 rendering 1 operation groups (tags)
2016/10/21 11:58:17 rendering 2 operations for operations
2016/10/21 11:58:17 rendering 3 templates for operation Item
2016/10/21 11:58:17 name field GetItems
2016/10/21 11:58:17 package field operations
2016/10/21 11:58:17 creating "get_items_parameters.go" in "restapi/operations" as parameters
2016/10/21 11:58:17 name field GetItems
2016/10/21 11:58:17 package field operations
2016/10/21 11:58:17 creating "get_items_responses.go" in "restapi/operations" as responses
format "responses" failed: get_items_responses.go:29:14: expected type, found 'STRING' `json:"body,omitempty"` (and 8 more errors)
```

Problem seems to be with the `array $ref` schema linked to external schema file (https://github.com/jbub/swaggerepro/blob/master/swagger.yaml#L22-L25).
## Swagger specification

https://github.com/jbub/swaggerepro
## Steps to reproduce
1. Clone the repo.
2. Install go swagger version:
   
   ```
   version: 0.7.3
   commit: 01d9ee15ff01cdbfdc735d21949a7cc66ab6ab56
   ```
3. Run `swagger generate server -A Item -f ./swagger.yaml` from the root of the repo.

**Comment by casualjim** [comment] 2016-10-21 15:11
duplicate of: #331

**Closed** 2016-11-03 16:59 UTC
Labels: bug, duplicate
