### ISSUE TITLE
invalid character '-' in numeric literal ON WINDOWS

### ISSUE THREAD

**Issue by smartsoul** [go-swagger/go-swagger#2493] opened 2021-01-20 03:46 UTC
## Swagger specification
```
---
swagger: '2.0'
info:
  description: Test
  version: 0.0.1
  title: Test
host: test
basePath: /test/v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /test:
    post:
      operationId: test
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/TestRequest'
      responses:
        200:
          description: OK
definitions:
  TestRequest:
    type: object
    properties:
      name:
        type: string
```

## Steps to reproduce
swagger validate ./test.yaml

Message:
```
The swagger spec at "./test.yaml" is invalid against swagger specification 2.0.
See errors below:
- could not resolve reference in "/test".POST to $ref : invalid character '-' in numeric literal
```
It is passed on 0.25.0

## Environment
swagger version: 0.26.0
go version: 1.15.6
OS:   Windows 10 Pro 20H2

**Comment by aliakseiz** [comment] 2021-01-20 06:01
Looks like a duplicate of #2492 .

**Comment by fredbi** [comment] 2021-01-21 14:41
I've identified the root cause of this. The problem is a subtle race with various package level init() that set the spec loader.
The symptom you see is a yaml spec incorrectly loaded as json.

The work around pending the fix (probably over next week) is to convert your spec to json.

**Closed** 2021-01-23 21:31 UTC
Labels: Ref resolution, bug, duplicate, pending PR, windows
